// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * exists/No:0?: number // Exists/No: 0
 * year?: string // Year
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-AJZAESD4.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:advlogo
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/p7kzCR0XZMNWPk6EFU5s/OJimofMeMwWJXjPCX9CO/WXuZ0rXP8.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-i6TgC";
var variantClassNames = {
	f4RBbflWu: "framer-v-3o595a",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ existsNo0, height, id, width, year, ...props }) => {
	var _ref, _ref1;
	return {
		...props,
		VqIe4UKFy:
			(_ref = year !== null && year !== void 0 ? year : props.VqIe4UKFy) !==
				null && _ref !== void 0
				? _ref
				: "2021",
		xovltkhnl:
			(_ref1 =
				existsNo0 !== null && existsNo0 !== void 0
					? existsNo0
					: props.xovltkhnl) !== null && _ref1 !== void 0
				? _ref1
				: 1,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Variants = motion.create(React.Fragment);
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		xovltkhnl,
		VqIe4UKFy,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "f4RBbflWu",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-3o595a",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"f4RBbflWu"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							opacity: xovltkhnl,
							...style,
						}}
					>
						<motion.div
							className={"framer-1kpfjyy"}
							data-framer-name={"Year"}
							layoutDependency={layoutDependency}
							layoutId={"m9PzXftvu"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-q1ok6m"}
								data-framer-name={"2021"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"lbFwYvANv"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
									opacity: 0.95,
								}}
								text={VqIe4UKFy}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1xoeoxz"}
										data-styles-preset={"cD0evZgOT"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))",
										}}
									>
										{"2021"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-16bgfut"}
							data-framer-name={"Logoitself"}
							layoutDependency={layoutDependency}
							layoutId={"qZYx5fvMJ"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 172.5,
									intrinsicWidth: 843.5,
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											0 +
											20 +
											0,
									),
									pixelHeight: 345,
									pixelWidth: 1687,
									sizes: "126px",
									src: "https://framerusercontent.com/images/h0mGxDtI76nkphLVW6LNORkaXdA.png?scale-down-to=1024",
									srcSet:
										"https://framerusercontent.com/images/h0mGxDtI76nkphLVW6LNORkaXdA.png?scale-down-to=512 512w,https://framerusercontent.com/images/h0mGxDtI76nkphLVW6LNORkaXdA.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/h0mGxDtI76nkphLVW6LNORkaXdA.png 1687w",
								}}
								className={"framer-183fxrm"}
								data-framer-name={"exlogo"}
								layoutDependency={layoutDependency}
								layoutId={"vnTgeCnw1"}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-i6TgC.framer-up45w4, .framer-i6TgC .framer-up45w4 { display: block; }",
	".framer-i6TgC.framer-3o595a { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; max-width: 142.5px; overflow: hidden; padding: 0px; position: relative; width: 143px; }",
	".framer-i6TgC .framer-1kpfjyy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-i6TgC .framer-q1ok6m { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-i6TgC .framer-16bgfut { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 10px 0px 0px; position: relative; width: 100%; }",
	".framer-i6TgC .framer-183fxrm { aspect-ratio: 4.889855072463768 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 26px); overflow: visible; position: relative; width: 126px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-i6TgC.framer-3o595a, .framer-i6TgC .framer-1kpfjyy, .framer-i6TgC .framer-16bgfut { gap: 0px; } .framer-i6TgC.framer-3o595a > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-i6TgC.framer-3o595a > :first-child { margin-top: 0px; } .framer-i6TgC.framer-3o595a > :last-child { margin-bottom: 0px; } .framer-i6TgC .framer-1kpfjyy > *, .framer-i6TgC .framer-16bgfut > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-i6TgC .framer-1kpfjyy > :first-child, .framer-i6TgC .framer-16bgfut > :first-child { margin-left: 0px; } .framer-i6TgC .framer-1kpfjyy > :last-child, .framer-i6TgC .framer-16bgfut > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerWXuZ0rXP8 = withCSS(Component, css2, "framer-i6TgC");
var stdin_default = FramerWXuZ0rXP8;
FramerWXuZ0rXP8.displayName = "Advlogo";
FramerWXuZ0rXP8.defaultProps = {
	height: 46,
	width: 142.5,
};
addPropertyControls(FramerWXuZ0rXP8, {
	xovltkhnl: {
		defaultValue: 1,
		max: 1,
		min: 0,
		step: 0.01,
		title: "Exists/No: 0",
		type: ControlType.Number,
	},
	VqIe4UKFy: {
		defaultValue: "2021",
		displayTextArea: false,
		title: "Year",
		type: ControlType.String,
	},
});
addFonts(
	FramerWXuZ0rXP8,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:advlogo
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AdvlogoFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var advlogo_default = ComponentWithRoot;
export { advlogo_default as default };
