// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
 * question?: string // Question
 * answer?: string // Answer
 * question2nd?: string // Question 2nd
 * answer2nd?: string // Answer 2nd
 * question3rd?: string // Question 3rd
 * answer3rd?: string // Answer 3rd
 * question4th?: string // Question 4th
 * answer4th?: string // Answer 4th
 * question5th?: string // Question 5th
 * answer5th?: string // Answer 5th
 * question6th?: string // Question 6th
 * answer6th?: string // Answer 6th
 * question7th?: string // Question 7th
 * answer7th?: string // Answer 7th
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-IJTBURAD.js";
import { className, css, fonts } from "./chunks/chunk-RNBS6EVX.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FRA4GJSE.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:all-questions
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/sfpC7THsukZVcszOPwbF/NQsKwEH7pqIMjoUQE4C1/tBycl3qMk.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/h8ioHyt4BUxuvVCE1Q10/aTM6mEMGlM19JjX8exDe/AvoidLayoutJumping_Prod.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { useEffect, useRef } from "react";
function AvoidLayoutJumping({ direction, style }) {
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const ref = useRef(null);
	const rafId = useRef();
	const vertical = direction === "vertical" || direction === "both";
	const horizontal = direction === "horizontal" || direction === "both";
	useEffect(() => {
		if (isCanvas) return;
		const parent = ref.current?.parentElement?.parentElement;
		if (!parent) return;
		const container = parent.parentElement;
		if (!container) return;
		const updateSize = () => {
			const rect = parent.getBoundingClientRect();
			if (horizontal) {
				container.style.width = `${rect.width}px`;
			}
			if (vertical) {
				container.style.height = `${rect.height}px`;
			}
			rafId.current = requestAnimationFrame(updateSize);
		};
		rafId.current = requestAnimationFrame(updateSize);
		return () => {
			if (rafId.current) {
				cancelAnimationFrame(rafId.current);
			}
			if (container) {
				if (horizontal) {
					container.style.width = "";
				}
				if (vertical) {
					container.style.height = "";
				}
			}
		};
	}, [direction]);
	return (
		<div
			ref={ref}
			style={{
				...style,
			}}
		/>
	);
}
AvoidLayoutJumping.displayName = "Layout Jump Preventer";
addPropertyControls(AvoidLayoutJumping, {
	direction: {
		type: ControlType.Enum,
		defaultValue: "vertical",
		options: ["vertical", "horizontal", "both"],
		optionTitles: ["Vertical", "Horizontal", "Both"],
		displaySegmentedControl: true,
		segmentedControlDirection: "vertical",
		// @ts-ignore
		optionIcons: [
			"direction-vertical",
			"direction-horizontal",
			"direction-all",
		],
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/OQFacVCJvlJojxzMa8dc/CNOjVCyxl7mWT9JrRQy9/dec3hfzRH.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	getFontsFromSharedStyle,
	RichText,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var cycleOrder = ["yRavfcwdI", "JGfKCoNgX", "wAA7n5ywX", "Pov4_Hcfw"];
var serializationHash = "framer-FF86P";
var variantClassNames = {
	JGfKCoNgX: "framer-v-1xn6u3m",
	Pov4_Hcfw: "framer-v-1cnkx03",
	wAA7n5ywX: "framer-v-16mo38g",
	yRavfcwdI: "framer-v-1u8a7dk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: -85,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop open": "wAA7n5ywX",
	"Phone open": "Pov4_Hcfw",
	Desktop: "yRavfcwdI",
	Phone: "JGfKCoNgX",
};
var getProps = ({ answer, height, id, question, visible, width, ...props }) => {
	return {
		...props,
		gIah5O0Ns: answer ?? props.gIah5O0Ns ?? "Answer",
		tmeF8zBnz: visible ?? props.tmeF8zBnz ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "yRavfcwdI",
		xea0qweof: question ?? props.xea0qweof ?? "Question",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		xea0qweof,
		gIah5O0Ns,
		tmeF8zBnz,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "yRavfcwdI",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapztiwu4 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("yRavfcwdI");
	});
	const onTap11a6zwz = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("JGfKCoNgX");
	});
	const onTapumjus5 = activeVariantCallback(async (...args) => {
		setVariant("wAA7n5ywX");
	});
	const onTap9xo91t = activeVariantCallback(async (...args) => {
		setVariant("Pov4_Hcfw");
	});
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["wAA7n5ywX", "Pov4_Hcfw"].includes(baseVariant)) return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1u8a7dk",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"yRavfcwdI"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								JGfKCoNgX: {
									"data-framer-name": "Phone",
								},
								Pov4_Hcfw: {
									"data-framer-name": "Phone open",
									"data-highlight": true,
									onTap: onTap11a6zwz,
								},
								wAA7n5ywX: {
									"data-framer-name": "Desktop open",
									"data-highlight": true,
									onTap: onTapztiwu4,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1f9api4"}
							data-framer-name={"item"}
							layoutDependency={layoutDependency}
							layoutId={"AFqTbPK83"}
						>
							<motion.div
								className={"framer-lmczb2"}
								data-framer-name={"question"}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"zn7rOU6hi"}
								onTap={onTapumjus5}
								{...addPropertyOverrides(
									{
										JGfKCoNgX: {
											onTap: onTap9xo91t,
										},
										Pov4_Hcfw: {
											"data-highlight": void 0,
											onTap: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion.div
									className={"framer-1j5omiz"}
									data-framer-name={"text"}
									layoutDependency={layoutDependency}
									layoutId={"pPtFJTEZh"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1w58f8d"}
										data-framer-name={
											"What interior design services do you offer?"
										}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"bvGKHiySr"}
										style={{
											"--extracted-1eung3n":
												"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={xea0qweof}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												JGfKCoNgX: {
													children: (
														<React.Fragment>
															<motion.h5
																className={"framer-styles-preset-1cfzzvd"}
																data-styles-preset={"tnGzdFFgX"}
															>
																{"Question"}
															</motion.h5>
														</React.Fragment>
													),
												},
												Pov4_Hcfw: {
													children: (
														<React.Fragment>
															<motion.h5
																className={"framer-styles-preset-1cfzzvd"}
																data-styles-preset={"tnGzdFFgX"}
															>
																{"Question"}
															</motion.h5>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h4
												className={"framer-styles-preset-1ep964h"}
												data-styles-preset={"LVzsaOw7J"}
												style={{
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
												}}
											>
												{"Question"}
											</motion.h4>
										</React.Fragment>
									</RichText>
								</motion.div>
								<SVG
									className={"framer-1qk0mmx"}
									data-framer-name={"expand"}
									fill={
										"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))"
									}
									intrinsicHeight={32}
									intrinsicWidth={32}
									layoutDependency={layoutDependency}
									layoutId={"DKEr3zRyY"}
									style={{
										rotate: 0,
									}}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 256 256"><path d="M228 128a12 12 0 0 1-12 12h-76v76a12 12 0 0 1-24 0v-76H40a12 12 0 0 1 0-24h76V40a12 12 0 0 1 24 0v76h76a12 12 0 0 1 12 12Z"/></svg>'
									}
									variants={{
										Pov4_Hcfw: {
											rotate: 45,
										},
										wAA7n5ywX: {
											rotate: -135,
										},
									}}
									withExternalLayout={true}
								/>
							</motion.div>
							{isDisplayed() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									className={"framer-trlv8j"}
									data-framer-appear-id={"trlv8j"}
									data-framer-name={"answer"}
									layoutDependency={layoutDependency}
									layoutId={"IBCqm0pjr"}
									{...addPropertyOverrides(
										{
											wAA7n5ywX: {
												__perspectiveFX: false,
												__smartComponentFX: true,
												__targetOpacity: 1,
												animate: animation,
												initial: animation1,
												optimized: true,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									{tmeF8zBnz && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1d051i6"}
											data-framer-name={
												"What interior design services do you offer?"
											}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"XX1tcKlRk"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135))",
												"--framer-paragraph-spacing": "0px",
											}}
											text={gIah5O0Ns}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													Pov4_Hcfw: {
														children: (
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector": "SW50ZXItTWVkaXVt",
																		"--framer-font-family":
																			'"Inter", "Inter Placeholder", sans-serif',
																		"--framer-font-size": "14px",
																		"--framer-font-weight": "500",
																		"--framer-letter-spacing": "-0.03em",
																		"--framer-line-height": "24px",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
																	}}
																>
																	{"Answer"}
																</motion.p>
															</React.Fragment>
														),
														fonts: ["Inter-Medium"],
													},
													wAA7n5ywX: {
														children: (
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector": "SW50ZXItTWVkaXVt",
																		"--framer-font-family":
																			'"Inter", "Inter Placeholder", sans-serif',
																		"--framer-font-size": "17px",
																		"--framer-font-weight": "500",
																		"--framer-letter-spacing": "-0.03em",
																		"--framer-line-height": "32px",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
																	}}
																>
																	{"Answer"}
																</motion.p>
															</React.Fragment>
														),
														fonts: ["Inter-Medium"],
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-5vtfax"}
													data-styles-preset={"xHNsUW18k"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
													}}
												>
													{"Answer"}
												</motion.p>
											</React.Fragment>
										</RichText>
									)}
								</MotionDivWithFXWithOptimizedAppearEffect>
							)}
						</motion.div>
						<motion.div
							className={"framer-rhm4kb"}
							data-framer-name={"line"}
							layoutDependency={layoutDependency}
							layoutId={"nGH69jmA4"}
							style={{
								backgroundColor:
									"var(--token-544f42e5-41ad-4707-98e6-458c7730fe9a, rgb(214, 219, 220))",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-FF86P.framer-1fbszwt, .framer-FF86P .framer-1fbszwt { display: block; }",
	".framer-FF86P.framer-1u8a7dk { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 995px; }",
	".framer-FF86P .framer-1f9api4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-FF86P .framer-lmczb2 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px 18px 0px 0px; position: relative; width: 100%; }",
	".framer-FF86P .framer-1j5omiz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 0px 0px; position: relative; width: 1px; }",
	".framer-FF86P .framer-1w58f8d, .framer-FF86P .framer-1d051i6 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-FF86P .framer-1qk0mmx { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }",
	".framer-FF86P .framer-trlv8j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px 18px 0px 0px; position: relative; width: 100%; }",
	".framer-FF86P .framer-rhm4kb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-FF86P.framer-1u8a7dk, .framer-FF86P .framer-1f9api4, .framer-FF86P .framer-1j5omiz, .framer-FF86P .framer-rhm4kb { gap: 0px; } .framer-FF86P.framer-1u8a7dk > * { margin: 0px; margin-bottom: calc(36px / 2); margin-top: calc(36px / 2); } .framer-FF86P.framer-1u8a7dk > :first-child, .framer-FF86P .framer-1f9api4 > :first-child { margin-top: 0px; } .framer-FF86P.framer-1u8a7dk > :last-child, .framer-FF86P .framer-1f9api4 > :last-child { margin-bottom: 0px; } .framer-FF86P .framer-1f9api4 > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-FF86P .framer-1j5omiz > *, .framer-FF86P .framer-rhm4kb > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-FF86P .framer-1j5omiz > :first-child, .framer-FF86P .framer-rhm4kb > :first-child { margin-left: 0px; } .framer-FF86P .framer-1j5omiz > :last-child, .framer-FF86P .framer-rhm4kb > :last-child { margin-right: 0px; } }",
	".framer-FF86P.framer-v-1xn6u3m.framer-1u8a7dk { gap: 24px; width: 326px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-FF86P.framer-v-1xn6u3m.framer-1u8a7dk { gap: 0px; } .framer-FF86P.framer-v-1xn6u3m.framer-1u8a7dk > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-FF86P.framer-v-1xn6u3m.framer-1u8a7dk > :first-child { margin-top: 0px; } .framer-FF86P.framer-v-1xn6u3m.framer-1u8a7dk > :last-child { margin-bottom: 0px; } }",
	".framer-FF86P.framer-v-16mo38g.framer-1u8a7dk { cursor: pointer; width: 995px; }",
	".framer-FF86P.framer-v-16mo38g .framer-1f9api4 { gap: 42px; }",
	".framer-FF86P.framer-v-16mo38g .framer-trlv8j { padding: 0px 80px 10px 0px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-FF86P.framer-v-16mo38g .framer-1f9api4 { gap: 0px; } .framer-FF86P.framer-v-16mo38g .framer-1f9api4 > * { margin: 0px; margin-bottom: calc(42px / 2); margin-top: calc(42px / 2); } .framer-FF86P.framer-v-16mo38g .framer-1f9api4 > :first-child { margin-top: 0px; } .framer-FF86P.framer-v-16mo38g .framer-1f9api4 > :last-child { margin-bottom: 0px; } }",
	".framer-FF86P.framer-v-1cnkx03.framer-1u8a7dk { cursor: pointer; gap: 24px; width: 326px; }",
	".framer-FF86P.framer-v-1cnkx03 .framer-1f9api4 { gap: 28px; }",
	".framer-FF86P.framer-v-1cnkx03 .framer-lmczb2 { cursor: unset; }",
	".framer-FF86P.framer-v-1cnkx03 .framer-trlv8j { padding: 0px 39px 4px 0px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-FF86P.framer-v-1cnkx03.framer-1u8a7dk, .framer-FF86P.framer-v-1cnkx03 .framer-1f9api4 { gap: 0px; } .framer-FF86P.framer-v-1cnkx03.framer-1u8a7dk > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-FF86P.framer-v-1cnkx03.framer-1u8a7dk > :first-child, .framer-FF86P.framer-v-1cnkx03 .framer-1f9api4 > :first-child { margin-top: 0px; } .framer-FF86P.framer-v-1cnkx03.framer-1u8a7dk > :last-child, .framer-FF86P.framer-v-1cnkx03 .framer-1f9api4 > :last-child { margin-bottom: 0px; } .framer-FF86P.framer-v-1cnkx03 .framer-1f9api4 > * { margin: 0px; margin-bottom: calc(28px / 2); margin-top: calc(28px / 2); } }",
	...css,
	...css3,
	...css2,
];
var Framerdec3hfzRH = withCSS(Component, css4, "framer-FF86P");
var stdin_default = Framerdec3hfzRH;
Framerdec3hfzRH.displayName = "Question item";
Framerdec3hfzRH.defaultProps = {
	height: 69,
	width: 994.5,
};
addPropertyControls2(Framerdec3hfzRH, {
	variant: {
		options: ["yRavfcwdI", "JGfKCoNgX", "wAA7n5ywX", "Pov4_Hcfw"],
		optionTitles: ["Desktop", "Phone", "Desktop open", "Phone open"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	xea0qweof: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question",
		type: ControlType2.String,
	},
	gIah5O0Ns: {
		defaultValue: "Answer",
		displayTextArea: false,
		title: "Answer",
		type: ControlType2.String,
	},
	tmeF8zBnz: {
		defaultValue: true,
		title: "Visible",
		type: ControlType2.Boolean,
	},
});
addFonts(
	Framerdec3hfzRH,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/sfpC7THsukZVcszOPwbF/NQsKwEH7pqIMjoUQE4C1/tBycl3qMk.js
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping);
var QuestionItemFonts = getFonts(stdin_default);
var cycleOrder2 = ["QNTUaa5_9", "S3TKl0Ina"];
var serializationHash2 = "framer-AYkzn";
var variantClassNames2 = {
	QNTUaa5_9: "framer-v-1htlpms",
	S3TKl0Ina: "framer-v-7rj7vs",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "QNTUaa5_9",
	Phone: "S3TKl0Ina",
};
var getProps2 = ({
	answer,
	answer2Nd,
	answer3Rd,
	answer4Th,
	answer5Th,
	answer6Th,
	answer7Th,
	height,
	id,
	question,
	question2Nd,
	question3Rd,
	question4Th,
	question5Th,
	question6Th,
	question7Th,
	width,
	...props
}) => {
	return {
		...props,
		cn67crow9: question6Th ?? props.cn67crow9 ?? "Question",
		EO8I8UfQY: answer5Th ?? props.EO8I8UfQY ?? "Answer",
		hkyE4mYor: question7Th ?? props.hkyE4mYor ?? "Question",
		IIgIrSUCX: question2Nd ?? props.IIgIrSUCX ?? "Question",
		J4Ny3qZcD: answer ?? props.J4Ny3qZcD ?? "Answer",
		KRoHVGxqe: question5Th ?? props.KRoHVGxqe ?? "Question",
		lVPIVBLhj: question4Th ?? props.lVPIVBLhj ?? "Question",
		M11ULuVyK: answer2Nd ?? props.M11ULuVyK ?? "Answer",
		ORLtXn6n5: question3Rd ?? props.ORLtXn6n5 ?? "Question",
		PTcm3l8dC: question ?? props.PTcm3l8dC ?? "Question",
		qImC3S_Ej: answer3Rd ?? props.qImC3S_Ej ?? "Answer",
		qzr9XvkOS: answer6Th ?? props.qzr9XvkOS ?? "Answer",
		tafnoNbXt: answer4Th ?? props.tafnoNbXt ?? "Answer",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "QNTUaa5_9",
		vrYU198GD: answer7Th ?? props.vrYU198GD ?? "Answer",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		PTcm3l8dC,
		J4Ny3qZcD,
		IIgIrSUCX,
		M11ULuVyK,
		ORLtXn6n5,
		qImC3S_Ej,
		lVPIVBLhj,
		tafnoNbXt,
		KRoHVGxqe,
		EO8I8UfQY,
		cn67crow9,
		qzr9XvkOS,
		hkyE4mYor,
		vrYU198GD,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "QNTUaa5_9",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const visible = isSet(J4Ny3qZcD);
	const visible1 = isSet(IIgIrSUCX);
	const visible2 = isSet(ORLtXn6n5);
	const visible3 = isSet(lVPIVBLhj);
	const visible4 = isSet(KRoHVGxqe);
	const visible5 = isSet(cn67crow9);
	const isDisplayed = (value) => {
		if (baseVariant === "S3TKl0Ina") return value;
		return false;
	};
	const visible6 = isSet(hkyE4mYor);
	const isDisplayed1 = (value) => {
		if (baseVariant === "S3TKl0Ina") return false;
		return value;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1htlpms",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"QNTUaa5_9"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								S3TKl0Ina: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1pyz7cw-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"ZBNkxbXPr-container"}
								nodeId={"ZBNkxbXPr"}
								rendersWithMotion={true}
								scopeId={"tBycl3qMk"}
								transformTemplate={transformTemplate1}
							>
								<AvoidLayoutJumping
									direction={"vertical"}
									height={"100%"}
									id={"ZBNkxbXPr"}
									layoutId={"ZBNkxbXPr"}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						{visible && (
							<ComponentViewportProvider
								height={69}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 699) - 0 - 699) / 2 + 0 + 0)
								}
								{...addPropertyOverrides2(
									{
										S3TKl0Ina: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 487) - 0 - 627) / 2 +
													0 +
													0),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1l53rag-container"}
									layoutDependency={layoutDependency}
									layoutId={"q29yFlnHr-container"}
									nodeId={"q29yFlnHr"}
									rendersWithMotion={true}
									scopeId={"tBycl3qMk"}
								>
									{_jsx3(stdin_default, {
										gIah5O0Ns: J4Ny3qZcD,
										height: "100%",
										id: "q29yFlnHr",
										layoutId: "q29yFlnHr",
										style: {
											width: "100%",
										},
										tmeF8zBnz: true,
										variant: "yRavfcwdI",
										width: "100%",
										xea0qweof: PTcm3l8dC,
										...addPropertyOverrides2(
											{
												S3TKl0Ina: {
													variant: "JGfKCoNgX",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible1 && (
							<ComponentViewportProvider
								height={69}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 699) - 0 - 699) / 2 + 69 + 36)
								}
								{...addPropertyOverrides2(
									{
										S3TKl0Ina: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 487) - 0 - 627) / 2 +
													69 +
													24),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-apvb2q-container"}
									layoutDependency={layoutDependency}
									layoutId={"vOo6F3E_i-container"}
									nodeId={"vOo6F3E_i"}
									rendersWithMotion={true}
									scopeId={"tBycl3qMk"}
								>
									{_jsx3(stdin_default, {
										gIah5O0Ns: M11ULuVyK,
										height: "100%",
										id: "vOo6F3E_i",
										layoutId: "vOo6F3E_i",
										style: {
											width: "100%",
										},
										tmeF8zBnz: true,
										variant: "yRavfcwdI",
										width: "100%",
										xea0qweof: IIgIrSUCX,
										...addPropertyOverrides2(
											{
												S3TKl0Ina: {
													variant: "JGfKCoNgX",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible2 && (
							<ComponentViewportProvider
								height={69}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 699) - 0 - 699) / 2 +
										138 +
										72)
								}
								{...addPropertyOverrides2(
									{
										S3TKl0Ina: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 487) - 0 - 627) / 2 +
													138 +
													48),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1b1lz1y-container"}
									layoutDependency={layoutDependency}
									layoutId={"Lfw0QdZem-container"}
									nodeId={"Lfw0QdZem"}
									rendersWithMotion={true}
									scopeId={"tBycl3qMk"}
								>
									{_jsx3(stdin_default, {
										gIah5O0Ns: qImC3S_Ej,
										height: "100%",
										id: "Lfw0QdZem",
										layoutId: "Lfw0QdZem",
										style: {
											width: "100%",
										},
										tmeF8zBnz: true,
										variant: "yRavfcwdI",
										width: "100%",
										xea0qweof: ORLtXn6n5,
										...addPropertyOverrides2(
											{
												S3TKl0Ina: {
													variant: "JGfKCoNgX",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible3 && (
							<ComponentViewportProvider
								height={69}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 699) - 0 - 699) / 2 +
										207 +
										108)
								}
								{...addPropertyOverrides2(
									{
										S3TKl0Ina: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 487) - 0 - 627) / 2 +
													207 +
													72),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1h733yl-container"}
									layoutDependency={layoutDependency}
									layoutId={"TDmfdfAqe-container"}
									nodeId={"TDmfdfAqe"}
									rendersWithMotion={true}
									scopeId={"tBycl3qMk"}
								>
									{_jsx3(stdin_default, {
										gIah5O0Ns: tafnoNbXt,
										height: "100%",
										id: "TDmfdfAqe",
										layoutId: "TDmfdfAqe",
										style: {
											width: "100%",
										},
										tmeF8zBnz: true,
										variant: "yRavfcwdI",
										width: "100%",
										xea0qweof: lVPIVBLhj,
										...addPropertyOverrides2(
											{
												S3TKl0Ina: {
													variant: "JGfKCoNgX",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible4 && (
							<ComponentViewportProvider
								height={69}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 699) - 0 - 699) / 2 +
										276 +
										144)
								}
								{...addPropertyOverrides2(
									{
										S3TKl0Ina: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 487) - 0 - 627) / 2 +
													276 +
													96),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-zq7cfb-container"}
									layoutDependency={layoutDependency}
									layoutId={"VnCDtWgRf-container"}
									nodeId={"VnCDtWgRf"}
									rendersWithMotion={true}
									scopeId={"tBycl3qMk"}
								>
									{_jsx3(stdin_default, {
										gIah5O0Ns: EO8I8UfQY,
										height: "100%",
										id: "VnCDtWgRf",
										layoutId: "VnCDtWgRf",
										style: {
											width: "100%",
										},
										tmeF8zBnz: true,
										variant: "yRavfcwdI",
										width: "100%",
										xea0qweof: KRoHVGxqe,
										...addPropertyOverrides2(
											{
												S3TKl0Ina: {
													variant: "JGfKCoNgX",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{isDisplayed(visible5) && (
							<ComponentViewportProvider
								{...addPropertyOverrides2(
									{
										S3TKl0Ina: {
											height: 69,
											width: componentViewport?.width || "100vw",
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 487) - 0 - 627) / 2 +
													345 +
													120),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1ceqpo5-container"}
									layoutDependency={layoutDependency}
									layoutId={"lxl4IpDWC-container"}
									nodeId={"lxl4IpDWC"}
									rendersWithMotion={true}
									scopeId={"tBycl3qMk"}
								>
									{_jsx3(stdin_default, {
										gIah5O0Ns: EO8I8UfQY,
										height: "100%",
										id: "lxl4IpDWC",
										layoutId: "lxl4IpDWC",
										style: {
											width: "100%",
										},
										tmeF8zBnz: true,
										variant: "JGfKCoNgX",
										width: "100%",
										xea0qweof: KRoHVGxqe,
										...addPropertyOverrides2(
											{
												S3TKl0Ina: {
													gIah5O0Ns: qzr9XvkOS,
													xea0qweof: cn67crow9,
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{isDisplayed(visible6) && (
							<ComponentViewportProvider
								{...addPropertyOverrides2(
									{
										S3TKl0Ina: {
											height: 69,
											width: componentViewport?.width || "100vw",
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 487) - 0 - 627) / 2 +
													414 +
													144),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1b3p25o-container"}
									layoutDependency={layoutDependency}
									layoutId={"jBTQ4L15E-container"}
									nodeId={"jBTQ4L15E"}
									rendersWithMotion={true}
									scopeId={"tBycl3qMk"}
								>
									{_jsx3(stdin_default, {
										gIah5O0Ns: EO8I8UfQY,
										height: "100%",
										id: "jBTQ4L15E",
										layoutId: "jBTQ4L15E",
										style: {
											width: "100%",
										},
										tmeF8zBnz: true,
										variant: "JGfKCoNgX",
										width: "100%",
										xea0qweof: KRoHVGxqe,
										...addPropertyOverrides2(
											{
												S3TKl0Ina: {
													gIah5O0Ns: vrYU198GD,
													xea0qweof: hkyE4mYor,
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{isDisplayed1(visible5) && (
							<ComponentViewportProvider
								height={69}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 699) - 0 - 699) / 2 +
										345 +
										180)
								}
							>
								<SmartComponentScopedContainer
									className={"framer-16aq4g0-container"}
									layoutDependency={layoutDependency}
									layoutId={"qaiQAwYVB-container"}
									nodeId={"qaiQAwYVB"}
									rendersWithMotion={true}
									scopeId={"tBycl3qMk"}
								>
									{_jsx3(stdin_default, {
										gIah5O0Ns: qzr9XvkOS,
										height: "100%",
										id: "qaiQAwYVB",
										layoutId: "qaiQAwYVB",
										style: {
											width: "100%",
										},
										tmeF8zBnz: true,
										variant: "yRavfcwdI",
										width: "100%",
										xea0qweof: cn67crow9,
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{isDisplayed1(visible6) && (
							<ComponentViewportProvider
								height={69}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 699) - 0 - 699) / 2 +
										414 +
										216)
								}
							>
								<SmartComponentScopedContainer
									className={"framer-1hjtk6g-container"}
									layoutDependency={layoutDependency}
									layoutId={"Rr_GuI85y-container"}
									nodeId={"Rr_GuI85y"}
									rendersWithMotion={true}
									scopeId={"tBycl3qMk"}
								>
									{_jsx3(stdin_default, {
										gIah5O0Ns: vrYU198GD,
										height: "100%",
										id: "Rr_GuI85y",
										layoutId: "Rr_GuI85y",
										style: {
											width: "100%",
										},
										tmeF8zBnz: true,
										variant: "yRavfcwdI",
										width: "100%",
										xea0qweof: hkyE4mYor,
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-AYkzn.framer-1j45m9, .framer-AYkzn .framer-1j45m9 { display: block; }",
	".framer-AYkzn.framer-1htlpms { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 995px; }",
	".framer-AYkzn .framer-1pyz7cw-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: auto; z-index: 1; }",
	".framer-AYkzn .framer-1l53rag-container, .framer-AYkzn .framer-apvb2q-container, .framer-AYkzn .framer-1b1lz1y-container, .framer-AYkzn .framer-1h733yl-container, .framer-AYkzn .framer-zq7cfb-container, .framer-AYkzn .framer-1ceqpo5-container, .framer-AYkzn .framer-1b3p25o-container, .framer-AYkzn .framer-16aq4g0-container, .framer-AYkzn .framer-1hjtk6g-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-AYkzn.framer-v-7rj7vs.framer-1htlpms { gap: 24px; width: 326px; }",
];
var FramertBycl3qMk = withCSS2(Component2, css5, "framer-AYkzn");
var stdin_default2 = FramertBycl3qMk;
FramertBycl3qMk.displayName = "All questions";
FramertBycl3qMk.defaultProps = {
	height: 699,
	width: 994.5,
};
addPropertyControls3(FramertBycl3qMk, {
	variant: {
		options: ["QNTUaa5_9", "S3TKl0Ina"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	PTcm3l8dC: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question",
		type: ControlType3.String,
	},
	J4Ny3qZcD: {
		defaultValue: "Answer",
		displayTextArea: false,
		title: "Answer",
		type: ControlType3.String,
	},
	IIgIrSUCX: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question 2nd",
		type: ControlType3.String,
	},
	M11ULuVyK: {
		defaultValue: "Answer",
		displayTextArea: false,
		title: "Answer 2nd",
		type: ControlType3.String,
	},
	ORLtXn6n5: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question 3rd",
		type: ControlType3.String,
	},
	qImC3S_Ej: {
		defaultValue: "Answer",
		displayTextArea: false,
		title: "Answer 3rd",
		type: ControlType3.String,
	},
	lVPIVBLhj: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question 4th",
		type: ControlType3.String,
	},
	tafnoNbXt: {
		defaultValue: "Answer",
		displayTextArea: false,
		title: "Answer 4th",
		type: ControlType3.String,
	},
	KRoHVGxqe: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question 5th",
		type: ControlType3.String,
	},
	EO8I8UfQY: {
		defaultValue: "Answer",
		displayTextArea: false,
		title: "Answer 5th",
		type: ControlType3.String,
	},
	cn67crow9: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question 6th",
		type: ControlType3.String,
	},
	qzr9XvkOS: {
		defaultValue: "Answer",
		displayTextArea: false,
		title: "Answer 6th",
		type: ControlType3.String,
	},
	hkyE4mYor: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question 7th",
		type: ControlType3.String,
	},
	vrYU198GD: {
		defaultValue: "Answer",
		description:
			"Change all the info, add and hide items (to hide just delete a question text)",
		displayTextArea: false,
		title: "Answer 7th",
		type: ControlType3.String,
	},
});
addFonts2(
	FramertBycl3qMk,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LayoutJumpPreventerFonts,
		...QuestionItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:all-questions
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AllQuestionsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var all_questions_default = ComponentWithRoot;
export { all_questions_default as default };
