// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * text?: string // Text
 * link?: string // Link
}} Props

 */
import { stdin_default } from "./chunks/chunk-CVGMZKKV.js";
import { className, css, fonts } from "./chunks/chunk-HOYSAFYX.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:allproj-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8z4opzBtm8QRHPstDXya/7ayUiAODtCoMGtDcOqZA/b7KPYw8z2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ArrowFonts = getFonts(stdin_default);
var enabledGestures = {
	fmUdPQtIL: {
		hover: true,
	},
};
var serializationHash = "framer-XOi9M";
var variantClassNames = {
	fmUdPQtIL: "framer-v-i01jz6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, text, width, ...props }) => {
	return {
		...props,
		J9ttYcWrP: text ?? props.J9ttYcWrP ?? "Text",
		k1u4LN2oT: link ?? props.k1u4LN2oT,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		J9ttYcWrP,
		k1u4LN2oT,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "fmUdPQtIL",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={k1u4LN2oT}
						motionChild={true}
						nodeId={"fmUdPQtIL"}
						openInNewTab={false}
						scopeId={"b7KPYw8z2"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-i01jz6", className2, classNames)} framer-1u1ddzr`}
							data-framer-name={"Linkto"}
							layoutDependency={layoutDependency}
							layoutId={"fmUdPQtIL"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"fmUdPQtIL-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1k72dys"}
								data-framer-name={"textblock"}
								layoutDependency={layoutDependency}
								layoutId={"pIDxP7xIY"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-12avlqb"}
									data-framer-name={"All the Projects"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"QKE6CpmLw"}
									style={{
										"--extracted-1eung3n":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={J9ttYcWrP}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-cgx770"}
											data-styles-preset={"bLAu95yRo"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"All the Projects"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
							<ComponentViewportProvider
								height={32}
								width={"32px"}
								y={
									(componentViewport?.y || 0) +
									(0 + ((componentViewport?.height || 32) - 0 - 32) / 2)
								}
							>
								<SmartComponentScopedContainer
									className={"framer-1p6wpxl-container"}
									layoutDependency={layoutDependency}
									layoutId={"H1gpRZTjQ-container"}
									nodeId={"H1gpRZTjQ"}
									rendersWithMotion={true}
									scopeId={"b7KPYw8z2"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "H1gpRZTjQ",
										layoutId: "H1gpRZTjQ",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "igm3HeMFN",
										width: "100%",
										...addPropertyOverrides(
											{
												"fmUdPQtIL-hover": {
													variant: "tlYGW1ze_",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-XOi9M.framer-1u1ddzr, .framer-XOi9M .framer-1u1ddzr { display: block; }",
	".framer-XOi9M.framer-i01jz6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-XOi9M .framer-1k72dys { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-XOi9M .framer-12avlqb { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-XOi9M .framer-1p6wpxl-container { flex: none; height: 32px; position: relative; width: 32px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-XOi9M.framer-i01jz6, .framer-XOi9M .framer-1k72dys { gap: 0px; } .framer-XOi9M.framer-i01jz6 > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-XOi9M.framer-i01jz6 > :first-child, .framer-XOi9M .framer-1k72dys > :first-child { margin-left: 0px; } .framer-XOi9M.framer-i01jz6 > :last-child, .framer-XOi9M .framer-1k72dys > :last-child { margin-right: 0px; } .framer-XOi9M .framer-1k72dys > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	".framer-XOi9M.framer-v-i01jz6.hover.framer-i01jz6 { gap: 18px; }",
	".framer-XOi9M.framer-v-i01jz6.hover .framer-1k72dys { padding: 0px 0px 0px 2px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-XOi9M.framer-v-i01jz6.hover.framer-i01jz6 { gap: 0px; } .framer-XOi9M.framer-v-i01jz6.hover.framer-i01jz6 > * { margin: 0px; margin-left: calc(18px / 2); margin-right: calc(18px / 2); } .framer-XOi9M.framer-v-i01jz6.hover.framer-i01jz6 > :first-child { margin-left: 0px; } .framer-XOi9M.framer-v-i01jz6.hover.framer-i01jz6 > :last-child { margin-right: 0px; } }",
	...css,
];
var Framerb7KPYw8z2 = withCSS(Component, css2, "framer-XOi9M");
var stdin_default2 = Framerb7KPYw8z2;
Framerb7KPYw8z2.displayName = "Allproj button";
Framerb7KPYw8z2.defaultProps = {
	height: 32,
	width: 98.5,
};
addPropertyControls(Framerb7KPYw8z2, {
	J9ttYcWrP: {
		defaultValue: "Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	k1u4LN2oT: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	Framerb7KPYw8z2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ArrowFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:allproj-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AllprojButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var allproj_button_default = ComponentWithRoot;
export { allproj_button_default as default };
