// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'White - L' | 'White - R' | 'White - Small - L' | 'White - Small - R' | 'Grey - L' | 'Grey - R' | 'White - Gall' | 'White - Small - L - hov' | 'White - Small - R - hov' | 'White - Gall - hov' | 'White - L - inactive' | 'White - R - inactive' // Variant
 * click?: Function // Click
}} Props

 */
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:arrow
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/x90JG5SHN7qCVmRzUgDo/ONZpmkXmKubrKEyfJtUB/TEVdpPQVc.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	CHtlc67yu: {
		hover: true,
	},
	cNB0_kHyL: {
		hover: true,
	},
	dCGeaeiMy: {
		hover: true,
	},
	igm3HeMFN: {
		hover: true,
	},
	LTfMapzz7: {
		hover: true,
	},
	Ru_noWw7h: {
		hover: true,
	},
};
var cycleOrder = [
	"CHtlc67yu",
	"dCGeaeiMy",
	"cNB0_kHyL",
	"igm3HeMFN",
	"LTfMapzz7",
	"Ru_noWw7h",
	"XSD8vsDwv",
	"vTOFe9O7k",
	"tlYGW1ze_",
	"i86t6V8zT",
	"aGghoOIUh",
	"JxxCOgesD",
];
var serializationHash = "framer-mZkBQ";
var variantClassNames = {
	aGghoOIUh: "framer-v-1caqyjq",
	CHtlc67yu: "framer-v-8ztbh0",
	cNB0_kHyL: "framer-v-1cb9xod",
	dCGeaeiMy: "framer-v-tyn4lj",
	i86t6V8zT: "framer-v-df9cmr",
	igm3HeMFN: "framer-v-kui0rd",
	JxxCOgesD: "framer-v-q66gsf",
	LTfMapzz7: "framer-v-1wkvi71",
	Ru_noWw7h: "framer-v-n9yhyy",
	tlYGW1ze_: "framer-v-kdi0at",
	vTOFe9O7k: "framer-v-ms5i2n",
	XSD8vsDwv: "framer-v-3h0g6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.3,
	delay: 0,
	duration: 0.9,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var transformTemplate2 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Grey - L": "LTfMapzz7",
	"Grey - R": "Ru_noWw7h",
	"White - Gall - hov": "i86t6V8zT",
	"White - Gall": "XSD8vsDwv",
	"White - L - inactive": "aGghoOIUh",
	"White - L": "CHtlc67yu",
	"White - R - inactive": "JxxCOgesD",
	"White - R": "dCGeaeiMy",
	"White - Small - L - hov": "vTOFe9O7k",
	"White - Small - L": "cNB0_kHyL",
	"White - Small - R - hov": "tlYGW1ze_",
	"White - Small - R": "igm3HeMFN",
};
var getProps = ({ click, height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "CHtlc67yu",
		Y1dyXKurN: click ?? props.Y1dyXKurN,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, Y1dyXKurN, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "CHtlc67yu",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapxff8hc = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Y1dyXKurN) {
			const res = await Y1dyXKurN(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["XSD8vsDwv", "i86t6V8zT"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["XSD8vsDwv", "i86t6V8zT"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-8ztbh0",
							className,
							classNames,
						)}
						data-framer-name={"White - L"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"CHtlc67yu"}
						onTap={onTapxff8hc}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
							borderBottomLeftRadius: 32,
							borderBottomRightRadius: 32,
							borderTopLeftRadius: 32,
							borderTopRightRadius: 32,
							boxShadow: "0px 2px 1px -1px rgba(0, 0, 0, 0.06)",
							...style,
						}}
						variants={{
							"CHtlc67yu-hover": {
								boxShadow: "0px 2px 1px -1px rgba(0, 0, 0, 0.16)",
							},
							"dCGeaeiMy-hover": {
								boxShadow: "0px 2px 1px -1px rgba(0, 0, 0, 0.16)",
							},
							"igm3HeMFN-hover": {
								boxShadow: "0px 2px 1px -1px rgba(0, 0, 0, 0.16)",
							},
							cNB0_kHyL: {
								backgroundColor:
									"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
							},
							LTfMapzz7: {
								backgroundColor:
									"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
								boxShadow: "none",
							},
							Ru_noWw7h: {
								backgroundColor:
									"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
								boxShadow: "none",
							},
							tlYGW1ze_: {
								boxShadow: "0px 2px 1px -1px rgba(0, 0, 0, 0.16)",
							},
							vTOFe9O7k: {
								backgroundColor:
									"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
							},
						}}
						{...addPropertyOverrides(
							{
								"CHtlc67yu-hover": {
									"data-framer-name": void 0,
								},
								"cNB0_kHyL-hover": {
									"data-framer-name": void 0,
								},
								"dCGeaeiMy-hover": {
									"data-framer-name": void 0,
								},
								"igm3HeMFN-hover": {
									"data-framer-name": void 0,
								},
								"LTfMapzz7-hover": {
									"data-framer-name": void 0,
								},
								"Ru_noWw7h-hover": {
									"data-framer-name": void 0,
								},
								aGghoOIUh: {
									"data-framer-name": "White - L - inactive",
								},
								cNB0_kHyL: {
									"data-framer-name": "White - Small - L",
								},
								dCGeaeiMy: {
									"data-framer-name": "White - R",
								},
								i86t6V8zT: {
									"data-framer-name": "White - Gall - hov",
								},
								igm3HeMFN: {
									"data-framer-name": "White - Small - R",
								},
								JxxCOgesD: {
									"data-framer-name": "White - R - inactive",
								},
								LTfMapzz7: {
									"data-framer-name": "Grey - L",
								},
								Ru_noWw7h: {
									"data-framer-name": "Grey - R",
								},
								tlYGW1ze_: {
									"data-framer-name": "White - Small - R - hov",
								},
								vTOFe9O7k: {
									"data-framer-name": "White - Small - L - hov",
								},
								XSD8vsDwv: {
									"data-framer-name": "White - Gall",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<SVG
								className={"framer-1wgel58"}
								data-framer-name={"gall"}
								fill={"black"}
								intrinsicHeight={32}
								intrinsicWidth={32}
								layoutDependency={layoutDependency}
								layoutId={"Bs6mrtWAt"}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 256 256"><path d="M120 56v48a16 16 0 0 1-16 16H56a16 16 0 0 1-16-16V56a16 16 0 0 1 16-16h48a16 16 0 0 1 16 16Zm80-16h-48a16 16 0 0 0-16 16v48a16 16 0 0 0 16 16h48a16 16 0 0 0 16-16V56a16 16 0 0 0-16-16Zm-96 96H56a16 16 0 0 0-16 16v48a16 16 0 0 0 16 16h48a16 16 0 0 0 16-16v-48a16 16 0 0 0-16-16Zm96 0h-48a16 16 0 0 0-16 16v48a16 16 0 0 0 16 16h48a16 16 0 0 0 16-16v-48a16 16 0 0 0-16-16Z"/></svg>'
								}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										XSD8vsDwv: {
											fill: 'var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)) /* {"name":"Black"} */',
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						{isDisplayed1() && (
							<motion.div
								className={"framer-bo1lud"}
								data-framer-name={"arrow icon"}
								layoutDependency={layoutDependency}
								layoutId={"QwUkpYDp9"}
								style={{
									opacity: 1,
									rotate: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									"CHtlc67yu-hover": {
										opacity: 1,
										rotate: 0,
									},
									"cNB0_kHyL-hover": {
										opacity: 1,
									},
									"dCGeaeiMy-hover": {
										opacity: 1,
									},
									"igm3HeMFN-hover": {
										opacity: 1,
									},
									"LTfMapzz7-hover": {
										opacity: 1,
									},
									"Ru_noWw7h-hover": {
										opacity: 1,
									},
									aGghoOIUh: {
										opacity: 0.3,
										rotate: 0,
									},
									cNB0_kHyL: {
										rotate: 0,
									},
									dCGeaeiMy: {
										rotate: 180,
									},
									igm3HeMFN: {
										rotate: 180,
									},
									JxxCOgesD: {
										opacity: 0.3,
										rotate: 180,
									},
									LTfMapzz7: {
										rotate: 0,
									},
									Ru_noWw7h: {
										rotate: 180,
									},
									tlYGW1ze_: {
										rotate: 180,
									},
									vTOFe9O7k: {
										rotate: 0,
									},
								}}
								{...addPropertyOverrides(
									{
										igm3HeMFN: {
											transformTemplate: transformTemplate2,
										},
										tlYGW1ze_: {
											transformTemplate: transformTemplate2,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion.div
									className={"framer-1cumzxa"}
									layoutDependency={layoutDependency}
									layoutId={"XLFSQPecJ"}
									style={{
										backgroundColor:
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										borderBottomLeftRadius: 3,
										borderBottomRightRadius: 3,
										borderTopLeftRadius: 3,
										borderTopRightRadius: 3,
									}}
								/>
								<motion.div
									className={"framer-1nrp752"}
									layoutDependency={layoutDependency}
									layoutId={"gTdiRYIfD"}
									style={{
										backgroundColor:
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										borderBottomLeftRadius: 10,
										borderBottomRightRadius: 1,
										borderTopLeftRadius: 10,
										rotate: 135,
									}}
								/>
								<motion.div
									className={"framer-14a54k2"}
									layoutDependency={layoutDependency}
									layoutId={"MuFV88spE"}
									style={{
										backgroundColor:
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										borderBottomLeftRadius: 10,
										borderBottomRightRadius: 10,
										borderTopLeftRadius: 10,
										rotate: 225,
									}}
								/>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-mZkBQ.framer-hp6gnc, .framer-mZkBQ .framer-hp6gnc { display: block; }",
	".framer-mZkBQ.framer-8ztbh0 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 46px; justify-content: center; overflow: hidden; padding: 12px; position: relative; width: 46px; will-change: var(--framer-will-change-override, transform); }",
	".framer-mZkBQ .framer-1wgel58 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }",
	".framer-mZkBQ .framer-bo1lud { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; min-height: 20px; min-width: 20px; overflow: visible; padding: 0px; position: absolute; top: 50%; width: min-content; z-index: 1; }",
	".framer-mZkBQ .framer-1cumzxa { flex: none; height: 2px; left: 1px; overflow: visible; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 19px; z-index: 1; }",
	".framer-mZkBQ .framer-1nrp752 { flex: none; height: 2px; left: 0px; overflow: visible; position: absolute; top: 5px; width: 11px; z-index: 1; }",
	".framer-mZkBQ .framer-14a54k2 { bottom: 5px; flex: none; height: 2px; left: 0px; overflow: visible; position: absolute; width: 11px; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-mZkBQ.framer-8ztbh0, .framer-mZkBQ .framer-bo1lud { gap: 0px; } .framer-mZkBQ.framer-8ztbh0 > *, .framer-mZkBQ .framer-bo1lud > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-mZkBQ.framer-8ztbh0 > :first-child, .framer-mZkBQ .framer-bo1lud > :first-child { margin-left: 0px; } .framer-mZkBQ.framer-8ztbh0 > :last-child, .framer-mZkBQ .framer-bo1lud > :last-child { margin-right: 0px; } }",
	".framer-mZkBQ.framer-v-1cb9xod.framer-8ztbh0, .framer-mZkBQ.framer-v-kui0rd.framer-8ztbh0, .framer-mZkBQ.framer-v-3h0g6.framer-8ztbh0, .framer-mZkBQ.framer-v-ms5i2n.framer-8ztbh0, .framer-mZkBQ.framer-v-kdi0at.framer-8ztbh0, .framer-mZkBQ.framer-v-df9cmr.framer-8ztbh0 { height: 32px; width: 32px; }",
	".framer-mZkBQ.framer-v-1cb9xod .framer-bo1lud, .framer-mZkBQ.framer-v-ms5i2n .framer-bo1lud { left: 53%; }",
	".framer-mZkBQ.framer-v-1cb9xod .framer-1cumzxa, .framer-mZkBQ.framer-v-kui0rd .framer-1cumzxa { left: 2px; width: 15px; }",
	".framer-mZkBQ.framer-v-1cb9xod .framer-1nrp752, .framer-mZkBQ.framer-v-kui0rd .framer-1nrp752 { left: 1px; top: 6px; width: 9px; }",
	".framer-mZkBQ.framer-v-1cb9xod .framer-14a54k2, .framer-mZkBQ.framer-v-kui0rd .framer-14a54k2 { bottom: 6px; left: 1px; width: 9px; }",
	".framer-mZkBQ.framer-v-kui0rd .framer-bo1lud { left: 4px; }",
	".framer-mZkBQ.framer-v-3h0g6 .framer-1wgel58 { order: 0; }",
	".framer-mZkBQ.framer-v-ms5i2n .framer-1cumzxa { width: 25px; }",
	".framer-mZkBQ.framer-v-ms5i2n .framer-1nrp752, .framer-mZkBQ.framer-v-kdi0at .framer-1nrp752, .framer-mZkBQ.framer-v-1cb9xod.hover .framer-1nrp752, .framer-mZkBQ.framer-v-kui0rd.hover .framer-1nrp752 { left: 1px; top: 6px; width: 7px; }",
	".framer-mZkBQ.framer-v-ms5i2n .framer-14a54k2, .framer-mZkBQ.framer-v-kdi0at .framer-14a54k2, .framer-mZkBQ.framer-v-1cb9xod.hover .framer-14a54k2, .framer-mZkBQ.framer-v-kui0rd.hover .framer-14a54k2 { bottom: 6px; left: 1px; width: 7px; }",
	".framer-mZkBQ.framer-v-kdi0at .framer-bo1lud { left: 3px; }",
	".framer-mZkBQ.framer-v-kdi0at .framer-1cumzxa { width: 24px; }",
	".framer-mZkBQ.framer-v-df9cmr .framer-1wgel58 { height: var(--framer-aspect-ratio-supported, 24px); order: 0; width: 24px; }",
	".framer-mZkBQ.framer-v-8ztbh0.hover .framer-1cumzxa, .framer-mZkBQ.framer-v-tyn4lj.hover .framer-1cumzxa, .framer-mZkBQ.framer-v-1wkvi71.hover .framer-1cumzxa, .framer-mZkBQ.framer-v-n9yhyy.hover .framer-1cumzxa { width: 33px; }",
	".framer-mZkBQ.framer-v-8ztbh0.hover .framer-1nrp752, .framer-mZkBQ.framer-v-tyn4lj.hover .framer-1nrp752, .framer-mZkBQ.framer-v-1wkvi71.hover .framer-1nrp752, .framer-mZkBQ.framer-v-n9yhyy.hover .framer-1nrp752 { left: 1px; top: 6px; width: 8px; }",
	".framer-mZkBQ.framer-v-8ztbh0.hover .framer-14a54k2, .framer-mZkBQ.framer-v-tyn4lj.hover .framer-14a54k2, .framer-mZkBQ.framer-v-1wkvi71.hover .framer-14a54k2, .framer-mZkBQ.framer-v-n9yhyy.hover .framer-14a54k2 { bottom: 6px; left: 1px; width: 8px; }",
	".framer-mZkBQ.framer-v-1cb9xod.hover .framer-1cumzxa { left: 1px; width: 25px; }",
	".framer-mZkBQ.framer-v-kui0rd.hover .framer-1cumzxa { left: 1px; width: 24px; }",
];
var FramerTEVdpPQVc = withCSS(Component, css, "framer-mZkBQ");
var stdin_default = FramerTEVdpPQVc;
FramerTEVdpPQVc.displayName = "Arrow";
FramerTEVdpPQVc.defaultProps = {
	height: 46,
	width: 46,
};
addPropertyControls(FramerTEVdpPQVc, {
	variant: {
		options: [
			"CHtlc67yu",
			"dCGeaeiMy",
			"cNB0_kHyL",
			"igm3HeMFN",
			"LTfMapzz7",
			"Ru_noWw7h",
			"XSD8vsDwv",
			"vTOFe9O7k",
			"tlYGW1ze_",
			"i86t6V8zT",
			"aGghoOIUh",
			"JxxCOgesD",
		],
		optionTitles: [
			"White - L",
			"White - R",
			"White - Small - L",
			"White - Small - R",
			"Grey - L",
			"Grey - R",
			"White - Gall",
			"White - Small - L - hov",
			"White - Small - R - hov",
			"White - Gall - hov",
			"White - L - inactive",
			"White - R - inactive",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	Y1dyXKurN: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerTEVdpPQVc,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:arrow
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ArrowFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var arrow_default = ComponentWithRoot;
export { arrow_default as default };
