// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * name1st?: string // Name 1st
 * year1st?: string // Year 1st
 * descr1st?: string // Descr 1st
 * name2nd?: string // Name 2nd
 * year2nd?: string // Year 2nd
 * descr2nd?: string // Descr 2nd
 * name3rd?: string // Name 3rd
 * year3rd?: string // Year 3rd
 * descr3rd?: string // Descr 3rd
 * name4th?: string // Name 4th
 * year4th?: string // Year 4th
 * descr4th?: string // Descr 4th
 * lastname?: string // Lastname
 * lastyear?: string // Lastyear
 * lastdescr?: string // Lastdescr
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-IJTBURAD.js";
import { className, css, fonts } from "./chunks/chunk-RNBS6EVX.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FRA4GJSE.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:awards
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/or19ooobQqtvgEy1CDKN/Jvx79TTXmGeH67kHDvZx/Wi2COjdsi.js
import { jsx as _jsx3, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx3,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/cwQKUE3074mlzKnQqu5a/WlfYAxGd0exrgvzFUea7/c32n3iz8P.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["u5WUtWETT", "UHDMH34qX", "IOjAgHNAT", "p0cULwE1_"];
var serializationHash = "framer-1D5Us";
var variantClassNames = {
	IOjAgHNAT: "framer-v-16yogvc",
	p0cULwE1_: "framer-v-bxd4nh",
	u5WUtWETT: "framer-v-1d2ri09",
	UHDMH34qX: "framer-v-1j9vhat",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Small desktop": "UHDMH34qX",
	Desktop: "u5WUtWETT",
	Phone: "p0cULwE1_",
	Tablet: "IOjAgHNAT",
};
var getProps = ({
	height,
	id,
	lastdescr,
	lastname,
	lastyear,
	width,
	...props
}) => {
	return {
		...props,
		bSh47AAtr: lastname ?? props.bSh47AAtr ?? "Name",
		KFnf7sWoW: lastdescr ?? props.KFnf7sWoW ?? "Sometext",
		lMpj0GlMz: lastyear ?? props.lMpj0GlMz ?? "1900",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "u5WUtWETT",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Variants = motion.create(React.Fragment);
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		bSh47AAtr,
		lMpj0GlMz,
		KFnf7sWoW,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "u5WUtWETT",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1d2ri09",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"u5WUtWETT"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								IOjAgHNAT: {
									"data-framer-name": "Tablet",
								},
								p0cULwE1_: {
									"data-framer-name": "Phone",
								},
								UHDMH34qX: {
									"data-framer-name": "Small desktop",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1g0oxg9"}
							data-framer-name={"name"}
							layoutDependency={layoutDependency}
							layoutId={"P1GA_ZEJN"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1xoknb8"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"z1H7hG931"}
								style={{
									"--extracted-1eung3n":
										"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={bSh47AAtr}
								variants={{
									IOjAgHNAT: {
										"--extracted-1lwpl3i":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
									},
									p0cULwE1_: {
										"--extracted-1lwpl3i":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										IOjAgHNAT: {
											children: (
												<React.Fragment>
													<motion.h5
														className={"framer-styles-preset-1cfzzvd"}
														data-styles-preset={"tnGzdFFgX"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
														}}
													>
														{"SBID International Design Awards"}
													</motion.h5>
												</React.Fragment>
											),
										},
										p0cULwE1_: {
											children: (
												<React.Fragment>
													<motion.h5
														className={"framer-styles-preset-1cfzzvd"}
														data-styles-preset={"tnGzdFFgX"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
														}}
													>
														{"SBID International Design Awards"}
													</motion.h5>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-1ep964h"}
										data-styles-preset={"LVzsaOw7J"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
										}}
									>
										{"SBID International Design Awards"}
									</motion.h4>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-p6onkw"}
							data-framer-name={"descr"}
							layoutDependency={layoutDependency}
							layoutId={"yQEftfOEI"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-dxuf8e"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"nYHy67aY6"}
								style={{
									"--extracted-1eung3n":
										"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={lMpj0GlMz}
								variants={{
									IOjAgHNAT: {
										"--extracted-1lwpl3i":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
									},
									p0cULwE1_: {
										"--extracted-1lwpl3i":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										IOjAgHNAT: {
											children: (
												<React.Fragment>
													<motion.h5
														className={"framer-styles-preset-1cfzzvd"}
														data-styles-preset={"tnGzdFFgX"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
														}}
													>
														{"2019"}
													</motion.h5>
												</React.Fragment>
											),
										},
										p0cULwE1_: {
											children: (
												<React.Fragment>
													<motion.h5
														className={"framer-styles-preset-1cfzzvd"}
														data-styles-preset={"tnGzdFFgX"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
														}}
													>
														{"2019"}
													</motion.h5>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-1ep964h"}
										data-styles-preset={"LVzsaOw7J"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
										}}
									>
										{"2019"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-ahxmak"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"If7Q_1LJm"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={KFnf7sWoW}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-5vtfax"}
										data-styles-preset={"xHNsUW18k"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
										}}
									>
										{
											"Celebrates 15 years with a retrospective showcase of the company\u2019s most iconic projects and milestones."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-1D5Us.framer-1xrog7g, .framer-1D5Us .framer-1xrog7g { display: block; }",
	".framer-1D5Us.framer-1d2ri09 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 18px 0px 0px; position: relative; width: 940px; }",
	".framer-1D5Us .framer-1g0oxg9 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 0px 0px; position: relative; width: 1px; }",
	".framer-1D5Us .framer-1xoknb8 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-1D5Us .framer-p6onkw { align-content: center; align-items: center; display: flex; flex: 3 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 0px 0px; position: relative; width: 1px; }",
	".framer-1D5Us .framer-dxuf8e, .framer-1D5Us .framer-ahxmak { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-1D5Us.framer-1d2ri09, .framer-1D5Us .framer-1g0oxg9, .framer-1D5Us .framer-p6onkw { gap: 0px; } .framer-1D5Us.framer-1d2ri09 > * { margin: 0px; margin-left: calc(30px / 2); margin-right: calc(30px / 2); } .framer-1D5Us.framer-1d2ri09 > :first-child, .framer-1D5Us .framer-1g0oxg9 > :first-child { margin-left: 0px; } .framer-1D5Us.framer-1d2ri09 > :last-child, .framer-1D5Us .framer-1g0oxg9 > :last-child { margin-right: 0px; } .framer-1D5Us .framer-1g0oxg9 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-1D5Us .framer-p6onkw > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-1D5Us .framer-p6onkw > :first-child { margin-top: 0px; } .framer-1D5Us .framer-p6onkw > :last-child { margin-bottom: 0px; } }",
	".framer-1D5Us.framer-v-1j9vhat.framer-1d2ri09 { width: 846px; }",
	".framer-1D5Us.framer-v-16yogvc.framer-1d2ri09 { width: 746px; }",
	".framer-1D5Us.framer-v-bxd4nh.framer-1d2ri09 { flex-direction: column; gap: 16px; padding: 0px; width: 326px; }",
	".framer-1D5Us.framer-v-bxd4nh .framer-1g0oxg9 { flex: none; width: 100%; }",
	".framer-1D5Us.framer-v-bxd4nh .framer-p6onkw { flex: none; gap: 12px; padding: 0px; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-1D5Us.framer-v-bxd4nh.framer-1d2ri09, .framer-1D5Us.framer-v-bxd4nh .framer-p6onkw { gap: 0px; } .framer-1D5Us.framer-v-bxd4nh.framer-1d2ri09 > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-1D5Us.framer-v-bxd4nh.framer-1d2ri09 > :first-child, .framer-1D5Us.framer-v-bxd4nh .framer-p6onkw > :first-child { margin-top: 0px; } .framer-1D5Us.framer-v-bxd4nh.framer-1d2ri09 > :last-child, .framer-1D5Us.framer-v-bxd4nh .framer-p6onkw > :last-child { margin-bottom: 0px; } .framer-1D5Us.framer-v-bxd4nh .framer-p6onkw > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } }",
	...css,
	...css3,
	...css2,
];
var Framerc32n3iz8P = withCSS(Component, css4, "framer-1D5Us");
var stdin_default = Framerc32n3iz8P;
Framerc32n3iz8P.displayName = "Lastaward";
Framerc32n3iz8P.defaultProps = {
	height: 70,
	width: 940,
};
addPropertyControls(Framerc32n3iz8P, {
	variant: {
		options: ["u5WUtWETT", "UHDMH34qX", "IOjAgHNAT", "p0cULwE1_"],
		optionTitles: ["Desktop", "Small desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	bSh47AAtr: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Lastname",
		type: ControlType.String,
	},
	lMpj0GlMz: {
		defaultValue: "1900",
		displayTextArea: false,
		title: "Lastyear",
		type: ControlType.String,
	},
	KFnf7sWoW: {
		defaultValue: "Sometext",
		displayTextArea: false,
		title: "Lastdescr",
		type: ControlType.String,
	},
});
addFonts(
	Framerc32n3iz8P,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/DpFqknrVr227wBAZrDib/O8pLwFXaf0fTwqHS3lRn/W8EqnFNwJ.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";
var cycleOrder2 = ["Op3ocB3lq", "IXJpfn7eN", "ikDVYNM9o"];
var serializationHash2 = "framer-s2NOF";
var variantClassNames2 = {
	ikDVYNM9o: "framer-v-1homxq2",
	IXJpfn7eN: "framer-v-dtu9oz",
	Op3ocB3lq: "framer-v-1llbje6",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "Op3ocB3lq",
	Phone: "ikDVYNM9o",
	Tablet: "IXJpfn7eN",
};
var getProps2 = ({ descr, height, id, name1, width, year, ...props }) => {
	return {
		...props,
		BY9J_RVBE: descr ?? props.BY9J_RVBE ?? "Sometext",
		UA04GuYkE: year ?? props.UA04GuYkE ?? "1900",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "Op3ocB3lq",
		zPTufTgke: name1 ?? props.zPTufTgke ?? "Name",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		zPTufTgke,
		UA04GuYkE,
		BY9J_RVBE,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "Op3ocB3lq",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1llbje6",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Op3ocB3lq"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								ikDVYNM9o: {
									"data-framer-name": "Phone",
								},
								IXJpfn7eN: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-sy62sa"}
							data-framer-name={"award"}
							layoutDependency={layoutDependency}
							layoutId={"XXUN1YEvh"}
						>
							<motion2.div
								className={"framer-1772e44"}
								data-framer-name={"name"}
								layoutDependency={layoutDependency}
								layoutId={"I3ALyvh2t"}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1w5pgbc"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"RhoOSMhq4"}
									style={{
										"--extracted-1eung3n":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={zPTufTgke}
									variants={{
										ikDVYNM9o: {
											"--extracted-1lwpl3i":
												"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										},
										IXJpfn7eN: {
											"--extracted-1lwpl3i":
												"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides2(
										{
											ikDVYNM9o: {
												children: (
													<React2.Fragment>
														<motion2.h5
															className={"framer-styles-preset-1cfzzvd"}
															data-styles-preset={"tnGzdFFgX"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"Name"}
														</motion2.h5>
													</React2.Fragment>
												),
											},
											IXJpfn7eN: {
												children: (
													<React2.Fragment>
														<motion2.h5
															className={"framer-styles-preset-1cfzzvd"}
															data-styles-preset={"tnGzdFFgX"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"Name"}
														</motion2.h5>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.h4
											className={"framer-styles-preset-1ep964h"}
											data-styles-preset={"LVzsaOw7J"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"Name"}
										</motion2.h4>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
							<motion2.div
								className={"framer-1s5lhzo"}
								data-framer-name={"descr"}
								layoutDependency={layoutDependency}
								layoutId={"ikLi1kCDg"}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1oz82gc"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"cRIGsnk6v"}
									style={{
										"--extracted-1eung3n":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={UA04GuYkE}
									variants={{
										ikDVYNM9o: {
											"--extracted-1lwpl3i":
												"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										},
										IXJpfn7eN: {
											"--extracted-1lwpl3i":
												"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides2(
										{
											ikDVYNM9o: {
												children: (
													<React2.Fragment>
														<motion2.h5
															className={"framer-styles-preset-1cfzzvd"}
															data-styles-preset={"tnGzdFFgX"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"1900"}
														</motion2.h5>
													</React2.Fragment>
												),
											},
											IXJpfn7eN: {
												children: (
													<React2.Fragment>
														<motion2.h5
															className={"framer-styles-preset-1cfzzvd"}
															data-styles-preset={"tnGzdFFgX"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"1900"}
														</motion2.h5>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.h4
											className={"framer-styles-preset-1ep964h"}
											data-styles-preset={"LVzsaOw7J"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"1900"}
										</motion2.h4>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-198ln35"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"HDSqiowlW"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={BY9J_RVBE}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-5vtfax"}
											data-styles-preset={"xHNsUW18k"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
											}}
										>
											{"Sometext"}
										</motion2.p>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
						</motion2.div>
						<motion2.div
							className={"framer-6kpqet"}
							data-framer-name={"line"}
							layoutDependency={layoutDependency}
							layoutId={"PJ4E1lPtf"}
							style={{
								backgroundColor:
									"var(--token-544f42e5-41ad-4707-98e6-458c7730fe9a, rgb(214, 219, 220))",
							}}
						/>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-s2NOF.framer-1wh4s0n, .framer-s2NOF .framer-1wh4s0n { display: block; }",
	".framer-s2NOF.framer-1llbje6 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 940px; }",
	".framer-s2NOF .framer-sy62sa { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 18px 0px 0px; position: relative; width: 100%; }",
	".framer-s2NOF .framer-1772e44 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 0px 0px; position: relative; width: 1px; }",
	".framer-s2NOF .framer-1w5pgbc { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-s2NOF .framer-1s5lhzo { align-content: center; align-items: center; display: flex; flex: 3 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 0px 0px; position: relative; width: 1px; }",
	".framer-s2NOF .framer-1oz82gc, .framer-s2NOF .framer-198ln35 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-s2NOF .framer-6kpqet { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-s2NOF.framer-1llbje6, .framer-s2NOF .framer-sy62sa, .framer-s2NOF .framer-1772e44, .framer-s2NOF .framer-1s5lhzo, .framer-s2NOF .framer-6kpqet { gap: 0px; } .framer-s2NOF.framer-1llbje6 > * { margin: 0px; margin-bottom: calc(36px / 2); margin-top: calc(36px / 2); } .framer-s2NOF.framer-1llbje6 > :first-child, .framer-s2NOF .framer-1s5lhzo > :first-child { margin-top: 0px; } .framer-s2NOF.framer-1llbje6 > :last-child, .framer-s2NOF .framer-1s5lhzo > :last-child { margin-bottom: 0px; } .framer-s2NOF .framer-sy62sa > * { margin: 0px; margin-left: calc(30px / 2); margin-right: calc(30px / 2); } .framer-s2NOF .framer-sy62sa > :first-child, .framer-s2NOF .framer-1772e44 > :first-child, .framer-s2NOF .framer-6kpqet > :first-child { margin-left: 0px; } .framer-s2NOF .framer-sy62sa > :last-child, .framer-s2NOF .framer-1772e44 > :last-child, .framer-s2NOF .framer-6kpqet > :last-child { margin-right: 0px; } .framer-s2NOF .framer-1772e44 > *, .framer-s2NOF .framer-6kpqet > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-s2NOF .framer-1s5lhzo > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }",
	".framer-s2NOF.framer-v-dtu9oz.framer-1llbje6 { width: 746px; }",
	".framer-s2NOF.framer-v-1homxq2.framer-1llbje6 { width: 326px; }",
	".framer-s2NOF.framer-v-1homxq2 .framer-sy62sa { flex-direction: column; gap: 16px; padding: 0px; }",
	".framer-s2NOF.framer-v-1homxq2 .framer-1772e44 { flex: none; padding: 0px; width: 100%; }",
	".framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo { flex: none; gap: 8px; padding: 0px; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-s2NOF.framer-v-1homxq2 .framer-sy62sa, .framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo { gap: 0px; } .framer-s2NOF.framer-v-1homxq2 .framer-sy62sa > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-s2NOF.framer-v-1homxq2 .framer-sy62sa > :first-child, .framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo > :first-child { margin-top: 0px; } .framer-s2NOF.framer-v-1homxq2 .framer-sy62sa > :last-child, .framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo > :last-child { margin-bottom: 0px; } .framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } }",
	...css,
	...css3,
	...css2,
];
var FramerW8EqnFNwJ = withCSS2(Component2, css5, "framer-s2NOF");
var stdin_default2 = FramerW8EqnFNwJ;
FramerW8EqnFNwJ.displayName = "Award item";
FramerW8EqnFNwJ.defaultProps = {
	height: 107,
	width: 940,
};
addPropertyControls2(FramerW8EqnFNwJ, {
	variant: {
		options: ["Op3ocB3lq", "IXJpfn7eN", "ikDVYNM9o"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	zPTufTgke: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name",
		type: ControlType2.String,
	},
	UA04GuYkE: {
		defaultValue: "1900",
		displayTextArea: false,
		title: "Year",
		type: ControlType2.String,
	},
	BY9J_RVBE: {
		defaultValue: "Sometext",
		displayTextArea: false,
		title: "Descr",
		type: ControlType2.String,
	},
});
addFonts2(
	FramerW8EqnFNwJ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle2(fonts),
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/or19ooobQqtvgEy1CDKN/Jvx79TTXmGeH67kHDvZx/Wi2COjdsi.js
var AwardItemFonts = getFonts(stdin_default2);
var LastawardFonts = getFonts(stdin_default);
var cycleOrder3 = ["zOYqQZ76j", "B_5PKpPfR", "K8ShZXcA5"];
var serializationHash3 = "framer-bkiSf";
var variantClassNames3 = {
	B_5PKpPfR: "framer-v-x5kk3e",
	K8ShZXcA5: "framer-v-upim9a",
	zOYqQZ76j: "framer-v-1imskpk",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var humanReadableVariantMap3 = {
	Desktop: "zOYqQZ76j",
	Phone: "K8ShZXcA5",
	Tablet: "B_5PKpPfR",
};
var getProps3 = ({
	descr1St,
	descr2Nd,
	descr3Rd,
	descr4Th,
	height,
	id,
	lastdescr,
	lastname,
	lastyear,
	name1St,
	name2Nd,
	name3Rd,
	name4Th,
	width,
	year1St,
	year2Nd,
	year3Rd,
	year4Th,
	...props
}) => {
	return {
		...props,
		bc93rBP3l: lastyear ?? props.bc93rBP3l ?? "1900",
		CeMA6Rra8: descr4Th ?? props.CeMA6Rra8 ?? "Sometext",
		gCpNvcUab: year2Nd ?? props.gCpNvcUab ?? "1900",
		gEfweD40J: descr1St ?? props.gEfweD40J ?? "Sometext",
		gh2pqurd8: name1St ?? props.gh2pqurd8 ?? "Name",
		gzjlOfAE7: year1St ?? props.gzjlOfAE7 ?? "1900",
		ieC8BCMZI: name2Nd ?? props.ieC8BCMZI ?? "Name",
		MiMy_9B3N: year3Rd ?? props.MiMy_9B3N ?? "1900",
		PaK9gab7g: descr3Rd ?? props.PaK9gab7g ?? "Sometext",
		PbnTQjhh8: name4Th ?? props.PbnTQjhh8 ?? "Name",
		QKYu51nUR: lastdescr ?? props.QKYu51nUR ?? "Sometext",
		s3Fdj8TZQ: descr2Nd ?? props.s3Fdj8TZQ ?? "Sometext",
		ULG3nXoaH: name3Rd ?? props.ULG3nXoaH ?? "Name",
		variant:
			humanReadableVariantMap3[props.variant] ?? props.variant ?? "zOYqQZ76j",
		VNZRX3EaS: year4Th ?? props.VNZRX3EaS ?? "1900",
		xqs_cXtUx: lastname ?? props.xqs_cXtUx ?? "Name",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		gh2pqurd8,
		gzjlOfAE7,
		gEfweD40J,
		ieC8BCMZI,
		gCpNvcUab,
		s3Fdj8TZQ,
		ULG3nXoaH,
		MiMy_9B3N,
		PaK9gab7g,
		PbnTQjhh8,
		VNZRX3EaS,
		CeMA6Rra8,
		xqs_cXtUx,
		bc93rBP3l,
		QKYu51nUR,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder3,
		defaultVariant: "zOYqQZ76j",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	const visible = isSet(gh2pqurd8);
	const visible1 = isSet(ieC8BCMZI);
	const visible2 = isSet(ULG3nXoaH);
	const visible3 = isSet(PbnTQjhh8);
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-1imskpk",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"zOYqQZ76j"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides3(
							{
								B_5PKpPfR: {
									"data-framer-name": "Tablet",
								},
								K8ShZXcA5: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{visible && (
							<ComponentViewportProvider
								height={107}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 642) - 0 - 642) / 2 + 0 + 0)
								}
								{...addPropertyOverrides3(
									{
										B_5PKpPfR: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 602) - 0 - 642) / 2 +
													0 +
													0),
										},
										K8ShZXcA5: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 642) / 2 +
													0 +
													0),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-9569mv-container"}
									layoutDependency={layoutDependency}
									layoutId={"Kv0ZqyOXP-container"}
									nodeId={"Kv0ZqyOXP"}
									rendersWithMotion={true}
									scopeId={"Wi2COjdsi"}
								>
									{_jsx3(stdin_default2, {
										BY9J_RVBE: gEfweD40J,
										height: "100%",
										id: "Kv0ZqyOXP",
										layoutId: "Kv0ZqyOXP",
										style: {
											width: "100%",
										},
										UA04GuYkE: gzjlOfAE7,
										variant: "Op3ocB3lq",
										width: "100%",
										zPTufTgke: gh2pqurd8,
										...addPropertyOverrides3(
											{
												B_5PKpPfR: {
													variant: "IXJpfn7eN",
												},
												K8ShZXcA5: {
													variant: "ikDVYNM9o",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible1 && (
							<ComponentViewportProvider
								height={107}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 642) - 0 - 642) / 2 +
										107 +
										36)
								}
								{...addPropertyOverrides3(
									{
										B_5PKpPfR: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 602) - 0 - 642) / 2 +
													107 +
													36),
										},
										K8ShZXcA5: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 642) / 2 +
													107 +
													36),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-f442l3-container"}
									layoutDependency={layoutDependency}
									layoutId={"uS2KCQ_dj-container"}
									nodeId={"uS2KCQ_dj"}
									rendersWithMotion={true}
									scopeId={"Wi2COjdsi"}
								>
									{_jsx3(stdin_default2, {
										BY9J_RVBE: s3Fdj8TZQ,
										height: "100%",
										id: "uS2KCQ_dj",
										layoutId: "uS2KCQ_dj",
										style: {
											width: "100%",
										},
										UA04GuYkE: gCpNvcUab,
										variant: "Op3ocB3lq",
										width: "100%",
										zPTufTgke: ieC8BCMZI,
										...addPropertyOverrides3(
											{
												B_5PKpPfR: {
													variant: "IXJpfn7eN",
												},
												K8ShZXcA5: {
													variant: "ikDVYNM9o",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible2 && (
							<ComponentViewportProvider
								height={107}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 642) - 0 - 642) / 2 +
										214 +
										72)
								}
								{...addPropertyOverrides3(
									{
										B_5PKpPfR: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 602) - 0 - 642) / 2 +
													214 +
													72),
										},
										K8ShZXcA5: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 642) / 2 +
													214 +
													72),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-hqzlvm-container"}
									layoutDependency={layoutDependency}
									layoutId={"W7HtjjfEH-container"}
									nodeId={"W7HtjjfEH"}
									rendersWithMotion={true}
									scopeId={"Wi2COjdsi"}
								>
									{_jsx3(stdin_default2, {
										BY9J_RVBE: PaK9gab7g,
										height: "100%",
										id: "W7HtjjfEH",
										layoutId: "W7HtjjfEH",
										style: {
											width: "100%",
										},
										UA04GuYkE: MiMy_9B3N,
										variant: "Op3ocB3lq",
										width: "100%",
										zPTufTgke: ULG3nXoaH,
										...addPropertyOverrides3(
											{
												B_5PKpPfR: {
													variant: "IXJpfn7eN",
												},
												K8ShZXcA5: {
													variant: "ikDVYNM9o",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{visible3 && (
							<ComponentViewportProvider
								height={107}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 642) - 0 - 642) / 2 +
										321 +
										108)
								}
								{...addPropertyOverrides3(
									{
										B_5PKpPfR: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 602) - 0 - 642) / 2 +
													321 +
													108),
										},
										K8ShZXcA5: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 642) / 2 +
													321 +
													108),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-16vtcnm-container"}
									layoutDependency={layoutDependency}
									layoutId={"WU1ItxKcm-container"}
									nodeId={"WU1ItxKcm"}
									rendersWithMotion={true}
									scopeId={"Wi2COjdsi"}
								>
									{_jsx3(stdin_default2, {
										BY9J_RVBE: CeMA6Rra8,
										height: "100%",
										id: "WU1ItxKcm",
										layoutId: "WU1ItxKcm",
										style: {
											width: "100%",
										},
										UA04GuYkE: VNZRX3EaS,
										variant: "Op3ocB3lq",
										width: "100%",
										zPTufTgke: PbnTQjhh8,
										...addPropertyOverrides3(
											{
												B_5PKpPfR: {
													variant: "IXJpfn7eN",
												},
												K8ShZXcA5: {
													variant: "ikDVYNM9o",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						<motion3.div
							className={"framer-kvoq93"}
							data-framer-name={"awardline"}
							layoutDependency={layoutDependency}
							layoutId={"S5xvuhiZ2"}
						>
							<ComponentViewportProvider
								height={70}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 642) - 0 - 642) / 2 +
										428 +
										144) +
									0 +
									0
								}
								{...addPropertyOverrides3(
									{
										B_5PKpPfR: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 602) - 0 - 642) / 2 +
													428 +
													144) +
												0 +
												0,
										},
										K8ShZXcA5: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 642) / 2 +
													428 +
													144) +
												0 +
												0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-mvib7f-container"}
									layoutDependency={layoutDependency}
									layoutId={"IC723cire-container"}
									nodeId={"IC723cire"}
									rendersWithMotion={true}
									scopeId={"Wi2COjdsi"}
								>
									{_jsx3(stdin_default, {
										bSh47AAtr: xqs_cXtUx,
										height: "100%",
										id: "IC723cire",
										KFnf7sWoW: QKYu51nUR,
										layoutId: "IC723cire",
										lMpj0GlMz: bc93rBP3l,
										style: {
											width: "100%",
										},
										variant: "u5WUtWETT",
										width: "100%",
										...addPropertyOverrides3(
											{
												B_5PKpPfR: {
													variant: "IOjAgHNAT",
												},
												K8ShZXcA5: {
													variant: "p0cULwE1_",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion3.div>
					</motion3.div>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-bkiSf.framer-r8vqkm, .framer-bkiSf .framer-r8vqkm { display: block; }",
	".framer-bkiSf.framer-1imskpk { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; max-width: 940px; overflow: hidden; padding: 0px; position: relative; width: 940px; }",
	".framer-bkiSf .framer-9569mv-container, .framer-bkiSf .framer-f442l3-container, .framer-bkiSf .framer-hqzlvm-container, .framer-bkiSf .framer-16vtcnm-container, .framer-bkiSf .framer-mvib7f-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-bkiSf .framer-kvoq93 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-bkiSf.framer-1imskpk, .framer-bkiSf .framer-kvoq93 { gap: 0px; } .framer-bkiSf.framer-1imskpk > *, .framer-bkiSf .framer-kvoq93 > * { margin: 0px; margin-bottom: calc(36px / 2); margin-top: calc(36px / 2); } .framer-bkiSf.framer-1imskpk > :first-child, .framer-bkiSf .framer-kvoq93 > :first-child { margin-top: 0px; } .framer-bkiSf.framer-1imskpk > :last-child, .framer-bkiSf .framer-kvoq93 > :last-child { margin-bottom: 0px; } }",
	".framer-bkiSf.framer-v-x5kk3e.framer-1imskpk { max-width: 800px; width: 746px; }",
	".framer-bkiSf.framer-v-upim9a.framer-1imskpk { width: 326px; }",
];
var FramerWi2COjdsi = withCSS3(Component3, css6, "framer-bkiSf");
var stdin_default3 = FramerWi2COjdsi;
FramerWi2COjdsi.displayName = "Awards";
FramerWi2COjdsi.defaultProps = {
	height: 642,
	width: 940,
};
addPropertyControls3(FramerWi2COjdsi, {
	variant: {
		options: ["zOYqQZ76j", "B_5PKpPfR", "K8ShZXcA5"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	gh2pqurd8: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name 1st",
		type: ControlType3.String,
	},
	gzjlOfAE7: {
		defaultValue: "1900",
		displayTextArea: false,
		title: "Year 1st",
		type: ControlType3.String,
	},
	gEfweD40J: {
		defaultValue: "Sometext",
		displayTextArea: false,
		title: "Descr 1st",
		type: ControlType3.String,
	},
	ieC8BCMZI: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name 2nd",
		type: ControlType3.String,
	},
	gCpNvcUab: {
		defaultValue: "1900",
		displayTextArea: false,
		title: "Year 2nd",
		type: ControlType3.String,
	},
	s3Fdj8TZQ: {
		defaultValue: "Sometext",
		displayTextArea: false,
		title: "Descr 2nd",
		type: ControlType3.String,
	},
	ULG3nXoaH: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name 3rd",
		type: ControlType3.String,
	},
	MiMy_9B3N: {
		defaultValue: "1900",
		displayTextArea: false,
		title: "Year 3rd",
		type: ControlType3.String,
	},
	PaK9gab7g: {
		defaultValue: "Sometext",
		displayTextArea: false,
		title: "Descr 3rd",
		type: ControlType3.String,
	},
	PbnTQjhh8: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name 4th",
		type: ControlType3.String,
	},
	VNZRX3EaS: {
		defaultValue: "1900",
		displayTextArea: false,
		title: "Year 4th",
		type: ControlType3.String,
	},
	CeMA6Rra8: {
		defaultValue: "Sometext",
		displayTextArea: false,
		title: "Descr 4th",
		type: ControlType3.String,
	},
	xqs_cXtUx: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Lastname",
		type: ControlType3.String,
	},
	bc93rBP3l: {
		defaultValue: "1900",
		displayTextArea: false,
		title: "Lastyear",
		type: ControlType3.String,
	},
	QKYu51nUR: {
		defaultValue: "Sometext",
		description:
			"Change all the info, add and hide items (to hide just delete an event name)",
		displayTextArea: false,
		title: "Lastdescr",
		type: ControlType3.String,
	},
});
addFonts3(
	FramerWi2COjdsi,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...AwardItemFonts,
		...LastawardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:awards
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AwardsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var awards_default = ComponentWithRoot;
export { awards_default as default };
