// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * name?: string // Name
 * year?: string // Year
 * descr?: string // Descr
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-IJTBURAD.js";
import { className, css, fonts } from "./chunks/chunk-RNBS6EVX.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FRA4GJSE.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:award-item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ut8m7Kb8eoPFHvmxBSLj/8MJPvdlYp0rk50TqnW0X/W8EqnFNwJ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["Op3ocB3lq", "IXJpfn7eN", "ikDVYNM9o"];
var serializationHash = "framer-s2NOF";
var variantClassNames = {
	ikDVYNM9o: "framer-v-1homxq2",
	IXJpfn7eN: "framer-v-dtu9oz",
	Op3ocB3lq: "framer-v-1llbje6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "Op3ocB3lq",
	Phone: "ikDVYNM9o",
	Tablet: "IXJpfn7eN",
};
var getProps = ({ descr, height, id, name1, width, year, ...props }) => {
	return {
		...props,
		BY9J_RVBE: descr ?? props.BY9J_RVBE ?? "Sometext",
		UA04GuYkE: year ?? props.UA04GuYkE ?? "1900",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Op3ocB3lq",
		zPTufTgke: name1 ?? props.zPTufTgke ?? "Name",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		zPTufTgke,
		UA04GuYkE,
		BY9J_RVBE,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Op3ocB3lq",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1llbje6",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Op3ocB3lq"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								ikDVYNM9o: {
									"data-framer-name": "Phone",
								},
								IXJpfn7eN: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-sy62sa"}
							data-framer-name={"award"}
							layoutDependency={layoutDependency}
							layoutId={"XXUN1YEvh"}
						>
							<motion.div
								className={"framer-1772e44"}
								data-framer-name={"name"}
								layoutDependency={layoutDependency}
								layoutId={"I3ALyvh2t"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1w5pgbc"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"RhoOSMhq4"}
									style={{
										"--extracted-1eung3n":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={zPTufTgke}
									variants={{
										ikDVYNM9o: {
											"--extracted-1lwpl3i":
												"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										},
										IXJpfn7eN: {
											"--extracted-1lwpl3i":
												"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											ikDVYNM9o: {
												children: (
													<React.Fragment>
														<motion.h5
															className={"framer-styles-preset-1cfzzvd"}
															data-styles-preset={"tnGzdFFgX"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"Name"}
														</motion.h5>
													</React.Fragment>
												),
											},
											IXJpfn7eN: {
												children: (
													<React.Fragment>
														<motion.h5
															className={"framer-styles-preset-1cfzzvd"}
															data-styles-preset={"tnGzdFFgX"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"Name"}
														</motion.h5>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-1ep964h"}
											data-styles-preset={"LVzsaOw7J"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"Name"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1s5lhzo"}
								data-framer-name={"descr"}
								layoutDependency={layoutDependency}
								layoutId={"ikLi1kCDg"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1oz82gc"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"cRIGsnk6v"}
									style={{
										"--extracted-1eung3n":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={UA04GuYkE}
									variants={{
										ikDVYNM9o: {
											"--extracted-1lwpl3i":
												"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										},
										IXJpfn7eN: {
											"--extracted-1lwpl3i":
												"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											ikDVYNM9o: {
												children: (
													<React.Fragment>
														<motion.h5
															className={"framer-styles-preset-1cfzzvd"}
															data-styles-preset={"tnGzdFFgX"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"1900"}
														</motion.h5>
													</React.Fragment>
												),
											},
											IXJpfn7eN: {
												children: (
													<React.Fragment>
														<motion.h5
															className={"framer-styles-preset-1cfzzvd"}
															data-styles-preset={"tnGzdFFgX"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1lwpl3i, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"1900"}
														</motion.h5>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-1ep964h"}
											data-styles-preset={"LVzsaOw7J"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"1900"}
										</motion.h4>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-198ln35"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"HDSqiowlW"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={BY9J_RVBE}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-5vtfax"}
											data-styles-preset={"xHNsUW18k"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
											}}
										>
											{"Sometext"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-6kpqet"}
							data-framer-name={"line"}
							layoutDependency={layoutDependency}
							layoutId={"PJ4E1lPtf"}
							style={{
								backgroundColor:
									"var(--token-544f42e5-41ad-4707-98e6-458c7730fe9a, rgb(214, 219, 220))",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-s2NOF.framer-1wh4s0n, .framer-s2NOF .framer-1wh4s0n { display: block; }",
	".framer-s2NOF.framer-1llbje6 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 940px; }",
	".framer-s2NOF .framer-sy62sa { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 18px 0px 0px; position: relative; width: 100%; }",
	".framer-s2NOF .framer-1772e44 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 0px 0px; position: relative; width: 1px; }",
	".framer-s2NOF .framer-1w5pgbc { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-s2NOF .framer-1s5lhzo { align-content: center; align-items: center; display: flex; flex: 3 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 0px 0px; position: relative; width: 1px; }",
	".framer-s2NOF .framer-1oz82gc, .framer-s2NOF .framer-198ln35 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-s2NOF .framer-6kpqet { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-s2NOF.framer-1llbje6, .framer-s2NOF .framer-sy62sa, .framer-s2NOF .framer-1772e44, .framer-s2NOF .framer-1s5lhzo, .framer-s2NOF .framer-6kpqet { gap: 0px; } .framer-s2NOF.framer-1llbje6 > * { margin: 0px; margin-bottom: calc(36px / 2); margin-top: calc(36px / 2); } .framer-s2NOF.framer-1llbje6 > :first-child, .framer-s2NOF .framer-1s5lhzo > :first-child { margin-top: 0px; } .framer-s2NOF.framer-1llbje6 > :last-child, .framer-s2NOF .framer-1s5lhzo > :last-child { margin-bottom: 0px; } .framer-s2NOF .framer-sy62sa > * { margin: 0px; margin-left: calc(30px / 2); margin-right: calc(30px / 2); } .framer-s2NOF .framer-sy62sa > :first-child, .framer-s2NOF .framer-1772e44 > :first-child, .framer-s2NOF .framer-6kpqet > :first-child { margin-left: 0px; } .framer-s2NOF .framer-sy62sa > :last-child, .framer-s2NOF .framer-1772e44 > :last-child, .framer-s2NOF .framer-6kpqet > :last-child { margin-right: 0px; } .framer-s2NOF .framer-1772e44 > *, .framer-s2NOF .framer-6kpqet > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-s2NOF .framer-1s5lhzo > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }",
	".framer-s2NOF.framer-v-dtu9oz.framer-1llbje6 { width: 746px; }",
	".framer-s2NOF.framer-v-1homxq2.framer-1llbje6 { width: 326px; }",
	".framer-s2NOF.framer-v-1homxq2 .framer-sy62sa { flex-direction: column; gap: 16px; padding: 0px; }",
	".framer-s2NOF.framer-v-1homxq2 .framer-1772e44 { flex: none; padding: 0px; width: 100%; }",
	".framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo { flex: none; gap: 8px; padding: 0px; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-s2NOF.framer-v-1homxq2 .framer-sy62sa, .framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo { gap: 0px; } .framer-s2NOF.framer-v-1homxq2 .framer-sy62sa > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-s2NOF.framer-v-1homxq2 .framer-sy62sa > :first-child, .framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo > :first-child { margin-top: 0px; } .framer-s2NOF.framer-v-1homxq2 .framer-sy62sa > :last-child, .framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo > :last-child { margin-bottom: 0px; } .framer-s2NOF.framer-v-1homxq2 .framer-1s5lhzo > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } }",
	...css,
	...css3,
	...css2,
];
var FramerW8EqnFNwJ = withCSS(Component, css4, "framer-s2NOF");
var stdin_default = FramerW8EqnFNwJ;
FramerW8EqnFNwJ.displayName = "Award item";
FramerW8EqnFNwJ.defaultProps = {
	height: 107,
	width: 940,
};
addPropertyControls(FramerW8EqnFNwJ, {
	variant: {
		options: ["Op3ocB3lq", "IXJpfn7eN", "ikDVYNM9o"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	zPTufTgke: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	UA04GuYkE: {
		defaultValue: "1900",
		displayTextArea: false,
		title: "Year",
		type: ControlType.String,
	},
	BY9J_RVBE: {
		defaultValue: "Sometext",
		displayTextArea: false,
		title: "Descr",
		type: ControlType.String,
	},
});
addFonts(
	FramerW8EqnFNwJ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:award-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AwardItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var award_item_default = ComponentWithRoot;
export { award_item_default as default };
