// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image1st?: {src: string, srcSet?: string, alt?: string} // Image 1st
 * image2nd?: {src: string, srcSet?: string, alt?: string} // Image 2nd
 * image3rd?: {src: string, srcSet?: string, alt?: string} // Image 3rd
 * image4th?: {src: string, srcSet?: string, alt?: string} // Image 4th
 * image5th?: {src: string, srcSet?: string, alt?: string} // Image 5th
}} Props

 */
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:bannergallery
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lMLIzP2RqvkENivRdQl4/gtzHFuJXW06vdUseRADi/abgbJrOjP.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var serializationHash = "framer-mM2xe";
var variantClassNames = {
	bsMheF1mf: "framer-v-1kcidcy",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: -10,
	rotateX: 0,
	rotateY: 0,
	scale: 1.3,
	skewX: 0,
	skewY: 0,
	x: -80,
	y: 0,
};
var transition2 = {
	bounce: 0.1,
	delay: 0,
	duration: 1.8,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: -10,
	rotateX: 0,
	rotateY: 0,
	scale: 1.3,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: -80,
	y: 0,
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var animation2 = {
	opacity: 1,
	rotate: -4,
	rotateX: 0,
	rotateY: 0,
	scale: 1.2,
	skewX: 0,
	skewY: 0,
	x: 10,
	y: 0,
};
var animation3 = {
	opacity: 1,
	rotate: -4,
	rotateX: 0,
	rotateY: 0,
	scale: 1.2,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 10,
	y: 0,
};
var animation4 = {
	opacity: 1,
	rotate: -10,
	rotateX: 0,
	rotateY: 0,
	scale: 1.3,
	skewX: 0,
	skewY: 0,
	x: 30,
	y: 0,
};
var animation5 = {
	opacity: 1,
	rotate: -10,
	rotateX: 0,
	rotateY: 0,
	scale: 1.3,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 30,
	y: 0,
};
var animation6 = {
	opacity: 1,
	rotate: -5,
	rotateX: 0,
	rotateY: 0,
	scale: 1.4,
	skewX: 0,
	skewY: 0,
	x: -40,
	y: 0,
};
var animation7 = {
	opacity: 1,
	rotate: -5,
	rotateX: 0,
	rotateY: 0,
	scale: 1.4,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: -40,
	y: 0,
};
var animation8 = {
	opacity: 1,
	rotate: -25,
	rotateX: 0,
	rotateY: 0,
	scale: 1.45,
	skewX: 0,
	skewY: 0,
	x: 50,
	y: 0,
};
var animation9 = {
	opacity: 1,
	rotate: -25,
	rotateX: 0,
	rotateY: 0,
	scale: 1.45,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 50,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	image1St,
	image2Nd,
	image3Rd,
	image4Th,
	image5Th,
	width,
	...props
}) => {
	return {
		...props,
		aGefWwObZ: image5Th ??
			props.aGefWwObZ ?? {
				alt: "",
				pixelHeight: 1333,
				pixelWidth: 2e3,
				src: "https://framerusercontent.com/images/NSemvw4UmNjJQg8RVKJ6HWj5OKY.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/NSemvw4UmNjJQg8RVKJ6HWj5OKY.png?scale-down-to=512 512w,https://framerusercontent.com/images/NSemvw4UmNjJQg8RVKJ6HWj5OKY.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/NSemvw4UmNjJQg8RVKJ6HWj5OKY.png 2000w",
			},
		lhHw6Txis: image4Th ??
			props.lhHw6Txis ?? {
				alt: "",
				pixelHeight: 1333,
				pixelWidth: 2e3,
				src: "https://framerusercontent.com/images/EtUEVtQPGQU8kadhPFbJZU1C4E4.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/EtUEVtQPGQU8kadhPFbJZU1C4E4.png?scale-down-to=512 512w,https://framerusercontent.com/images/EtUEVtQPGQU8kadhPFbJZU1C4E4.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/EtUEVtQPGQU8kadhPFbJZU1C4E4.png 2000w",
			},
		mNDvJoV6k: image3Rd ??
			props.mNDvJoV6k ?? {
				alt: "",
				pixelHeight: 731,
				pixelWidth: 1178,
				src: "https://framerusercontent.com/images/JG76gmWGCXbSRSK0wWajck4VE.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/JG76gmWGCXbSRSK0wWajck4VE.png?scale-down-to=512 512w,https://framerusercontent.com/images/JG76gmWGCXbSRSK0wWajck4VE.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/JG76gmWGCXbSRSK0wWajck4VE.png 1178w",
			},
		TIef4Luxc: image1St ??
			props.TIef4Luxc ?? {
				alt: "",
				pixelHeight: 417,
				pixelWidth: 626,
				src: "https://framerusercontent.com/images/baNnhthugcGoM6GrHelOTb6lmP8.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/baNnhthugcGoM6GrHelOTb6lmP8.png?scale-down-to=512 512w,https://framerusercontent.com/images/baNnhthugcGoM6GrHelOTb6lmP8.png 626w",
			},
		vjqqeqHTi: image2Nd ??
			props.vjqqeqHTi ?? {
				alt: "",
				pixelHeight: 1333,
				pixelWidth: 2e3,
				src: "https://framerusercontent.com/images/jllilwLARge7NnVWlGbMhCmeeFU.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/jllilwLARge7NnVWlGbMhCmeeFU.png?scale-down-to=512 512w,https://framerusercontent.com/images/jllilwLARge7NnVWlGbMhCmeeFU.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/jllilwLARge7NnVWlGbMhCmeeFU.png 2000w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		TIef4Luxc,
		vjqqeqHTi,
		mNDvJoV6k,
		lhHw6Txis,
		aGefWwObZ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "bsMheF1mf",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1kcidcy",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"bsMheF1mf"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__exit={animation1}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-ekys5g"}
							data-framer-name={"instphoto1"}
							layoutDependency={layoutDependency}
							layoutId={"riSLwSS5U"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 3,
								borderBottomRightRadius: 3,
								borderTopLeftRadius: 3,
								borderTopRightRadius: 3,
								boxShadow:
									"2px 2px 2px 1px rgba(69, 66, 66, 0.06), 0px 4px 4px 0px rgba(0, 0, 0, 0.13)",
								rotate: -6,
							}}
						>
							<motion.div
								className={"framer-144tqy6"}
								data-framer-name={"inner"}
								layoutDependency={layoutDependency}
								layoutId={"xXNNqVP3L"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												((componentViewport?.height || 189) *
													0.5376344086021507 -
													((componentViewport?.height || 189) * 0.7) / 2) +
												4 +
												0 +
												((componentViewport?.height || 189) * 0.7 - 4) * 0.81 -
												111,
										),
										sizes: `calc(${componentViewport?.width || "100vw"} * 0.2486 + 78px)`,
										...toResponsiveImage(TIef4Luxc),
									}}
									className={"framer-1yp8lbg"}
									data-framer-name={"img1"}
									layoutDependency={layoutDependency}
									layoutId={"ov6mUZlna"}
								/>
							</motion.div>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation2}
							__framer__exit={animation3}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-b6mbv4"}
							data-framer-name={"instphoto3"}
							layoutDependency={layoutDependency}
							layoutId={"ZIH823Ey7"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 3,
								borderBottomRightRadius: 3,
								borderTopLeftRadius: 3,
								borderTopRightRadius: 3,
								boxShadow:
									"2px 2px 2px 1px rgba(69, 66, 66, 0.06), 0px 4px 4px 0px rgba(0, 0, 0, 0.13)",
								rotate: -2,
							}}
						>
							<motion.div
								className={"framer-45e102"}
								data-framer-name={"inner"}
								layoutDependency={layoutDependency}
								layoutId={"Exd8OF5uA"}
							>
								<Image
									background={{
										alt: "",
										fit: "fit",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												((componentViewport?.height || 189) *
													0.5591397849462367 -
													((componentViewport?.height || 189) * 0.6971) / 2) +
												4 +
												0 +
												-51.5,
										),
										sizes: `calc(${componentViewport?.width || "100vw"} * 0.2486 + 182px)`,
										...toResponsiveImage(mNDvJoV6k),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-1b5hunq"}
									data-framer-name={"img3"}
									layoutDependency={layoutDependency}
									layoutId={"v02DkbSmI"}
								/>
							</motion.div>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation4}
							__framer__exit={animation5}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-1ul28i7"}
							data-framer-name={"instphoto4"}
							layoutDependency={layoutDependency}
							layoutId={"EPDXZAqoN"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 3,
								borderBottomRightRadius: 3,
								borderTopLeftRadius: 3,
								borderTopRightRadius: 3,
								boxShadow:
									"2px 2px 2px 1px rgba(69, 66, 66, 0.06), 0px 4px 4px 0px rgba(0, 0, 0, 0.13)",
								rotate: 17,
							}}
						>
							<motion.div
								className={"framer-hic8i5"}
								data-framer-name={"inner"}
								layoutDependency={layoutDependency}
								layoutId={"H0Vo8aKP_"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												((componentViewport?.height || 189) *
													0.5215053763440862 -
													((componentViewport?.height || 189) * 0.6989) / 2) +
												4 +
												0 +
												-45.5,
										),
										sizes: `calc(${componentViewport?.width || "100vw"} * 0.2486 + 131px)`,
										...toResponsiveImage(lhHw6Txis),
									}}
									className={"framer-1bmptg6"}
									data-framer-name={"img4"}
									layoutDependency={layoutDependency}
									layoutId={"nAxdkCRsb"}
								/>
							</motion.div>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation6}
							__framer__exit={animation7}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-mvdxid"}
							data-framer-name={"instphoto2"}
							layoutDependency={layoutDependency}
							layoutId={"UKiDlCKIj"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 3,
								borderBottomRightRadius: 3,
								borderTopLeftRadius: 3,
								borderTopRightRadius: 3,
								boxShadow:
									"2px 2px 2px 1px rgba(69, 66, 66, 0.06), 0px 4px 4px 0px rgba(0, 0, 0, 0.13)",
								rotate: 8,
							}}
						>
							<motion.div
								className={"framer-2ose9n"}
								data-framer-name={"inner"}
								layoutDependency={layoutDependency}
								layoutId={"YL8VZ570l"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												((componentViewport?.height || 189) *
													0.4784946236559142 -
													((componentViewport?.height || 189) * 0.6989) / 2) +
												4 +
												0 +
												((componentViewport?.height || 189) * 0.6989 - 4) *
													0.81 -
												141.5,
										),
										sizes: `calc(${componentViewport?.width || "100vw"} * 0.2486 + 200.5px)`,
										...toResponsiveImage(vjqqeqHTi),
									}}
									className={"framer-1le4alb"}
									data-framer-name={"img2"}
									layoutDependency={layoutDependency}
									layoutId={"JrQ_MxqxB"}
								/>
							</motion.div>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation8}
							__framer__exit={animation9}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-3q99cs"}
							data-framer-name={"instphoto5"}
							layoutDependency={layoutDependency}
							layoutId={"tBWiL6GpZ"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 3,
								borderBottomRightRadius: 3,
								borderTopLeftRadius: 3,
								borderTopRightRadius: 3,
								boxShadow:
									"2px 2px 2px 1px rgba(69, 66, 66, 0.06), 0px 4px 4px 0px rgba(0, 0, 0, 0.13)",
								rotate: 9,
							}}
						>
							<motion.div
								className={"framer-141dztq"}
								data-framer-name={"inner"}
								layoutDependency={layoutDependency}
								layoutId={"Eyp_su5aE"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												((componentViewport?.height || 189) *
													0.4946236559139787 -
													((componentViewport?.height || 189) * 0.6989) / 2) +
												4 +
												0 +
												((componentViewport?.height || 189) * 0.6989 - 4) *
													0.81 -
												114.5,
										),
										sizes: `calc(${componentViewport?.width || "100vw"} * 0.2486 + 91px)`,
										...toResponsiveImage(aGefWwObZ),
									}}
									className={"framer-6argx8"}
									data-framer-name={"img5"}
									layoutDependency={layoutDependency}
									layoutId={"UAr3PufRL"}
								/>
							</motion.div>
						</MotionDivWithFX>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-mM2xe.framer-fdc7d5, .framer-mM2xe .framer-fdc7d5 { display: block; }",
	".framer-mM2xe.framer-1kcidcy { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 189px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 420px; }",
	".framer-mM2xe .framer-ekys5g { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 70%; justify-content: flex-start; left: calc(9.16767189384803% - 27.020506634499398% / 2); overflow: visible; padding: 4px 0px 0px 0px; position: absolute; top: calc(53.76344086021507% - 70% / 2); width: 27%; z-index: 1; }",
	".framer-mM2xe .framer-144tqy6, .framer-mM2xe .framer-45e102, .framer-mM2xe .framer-hic8i5, .framer-mM2xe .framer-2ose9n, .framer-mM2xe .framer-141dztq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 81%; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 92%; }",
	".framer-mM2xe .framer-1yp8lbg { aspect-ratio: 1.5036495479919334 / 1; bottom: -12px; flex: none; height: var(--framer-aspect-ratio-supported, 122px); left: -37px; position: absolute; right: -41px; z-index: 1; }",
	".framer-mM2xe .framer-b6mbv4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 70%; justify-content: flex-start; left: calc(49.93968636911944% - 27.020506634499398% / 2); overflow: visible; padding: 4px 0px 0px 0px; position: absolute; top: calc(55.91397849462367% - 69.70509383378017% / 2); width: 27%; z-index: 1; }",
	".framer-mM2xe .framer-1b5hunq { bottom: -15px; flex: none; left: -158px; position: absolute; right: -24px; top: -51px; z-index: 1; }",
	".framer-mM2xe .framer-1ul28i7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 70%; justify-content: flex-start; left: calc(75.51266586248494% - 27.020506634499398% / 2); overflow: visible; padding: 4px 0px 0px 0px; position: absolute; top: calc(52.15053763440862% - 69.89247311827957% / 2); width: 27%; z-index: 1; }",
	".framer-mM2xe .framer-1bmptg6 { aspect-ratio: 1.3054186444640856 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 181px); left: -43px; position: absolute; right: -87px; top: -45px; z-index: 1; }",
	".framer-mM2xe .framer-mvdxid { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 70%; justify-content: flex-start; left: calc(29.191797346200264% - 27.020506634499398% / 2); overflow: visible; padding: 4px 0px 0px 0px; position: absolute; top: calc(47.84946236559142% - 69.89247311827957% / 2); width: 27%; z-index: 1; }",
	".framer-mM2xe .framer-1le4alb { aspect-ratio: 1.5021832983731125 / 1; bottom: -63px; flex: none; height: var(--framer-aspect-ratio-supported, 203px); left: -60px; position: absolute; right: -140px; z-index: 1; }",
	".framer-mM2xe .framer-3q99cs { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 70%; justify-content: flex-start; left: calc(92.15922798552475% - 27.020506634499398% / 2); overflow: visible; padding: 4px 0px 0px 0px; position: absolute; top: calc(49.46236559139787% - 69.89247311827957% / 2); width: 27%; z-index: 1; }",
	".framer-mM2xe .framer-6argx8 { aspect-ratio: 1.4350650412667316 / 1; bottom: -23px; flex: none; height: var(--framer-aspect-ratio-supported, 136px); left: -80px; position: absolute; right: -10px; z-index: 1; }",
];
var FramerabgbJrOjP = withCSS(Component, css, "framer-mM2xe");
var stdin_default = FramerabgbJrOjP;
FramerabgbJrOjP.displayName = "Bannergallery";
FramerabgbJrOjP.defaultProps = {
	height: 189,
	width: 420,
};
addPropertyControls(FramerabgbJrOjP, {
	TIef4Luxc: {
		__defaultAssetReference:
			"data:framer/asset-reference,baNnhthugcGoM6GrHelOTb6lmP8.png?originalFilename=image+78.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,baNnhthugcGoM6GrHelOTb6lmP8.png?originalFilename=image+78.png&preferredSize=auto",
		},
		title: "Image 1st",
		type: ControlType.ResponsiveImage,
	},
	vjqqeqHTi: {
		__defaultAssetReference:
			"data:framer/asset-reference,jllilwLARge7NnVWlGbMhCmeeFU.png?originalFilename=image+79.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,jllilwLARge7NnVWlGbMhCmeeFU.png?originalFilename=image+79.png&preferredSize=auto",
		},
		title: "Image 2nd",
		type: ControlType.ResponsiveImage,
	},
	mNDvJoV6k: {
		__defaultAssetReference:
			"data:framer/asset-reference,JG76gmWGCXbSRSK0wWajck4VE.png?originalFilename=image+76.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,JG76gmWGCXbSRSK0wWajck4VE.png?originalFilename=image+76.png&preferredSize=auto",
		},
		title: "Image 3rd",
		type: ControlType.ResponsiveImage,
	},
	lhHw6Txis: {
		__defaultAssetReference:
			"data:framer/asset-reference,EtUEVtQPGQU8kadhPFbJZU1C4E4.png?originalFilename=image+11.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,EtUEVtQPGQU8kadhPFbJZU1C4E4.png?originalFilename=image+11.png&preferredSize=auto",
		},
		title: "Image 4th",
		type: ControlType.ResponsiveImage,
	},
	aGefWwObZ: {
		__defaultAssetReference:
			"data:framer/asset-reference,NSemvw4UmNjJQg8RVKJ6HWj5OKY.png?originalFilename=image.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,NSemvw4UmNjJQg8RVKJ6HWj5OKY.png?originalFilename=image.png&preferredSize=auto",
		},
		title: "Image 5th",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerabgbJrOjP,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:bannergallery
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BannergalleryFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var bannergallery_default = ComponentWithRoot;
export { bannergallery_default as default };
