// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-C6U7IFL3.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:button-for-form
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wlQDVemwQfJ3JBOO4VzX/zI39644mvaZfmrNSNRkP/mLgXWeWm5.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	Xh_OlxVRD: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"Xh_OlxVRD",
	"i5DA3SvqK",
	"mFU1YIo0W",
	"nfgIbSqZH",
	"mYWOgooNw",
];
var serializationHash = "framer-ycJBS";
var variantClassNames = {
	i5DA3SvqK: "framer-v-132odtq",
	mFU1YIo0W: "framer-v-10qbtw2",
	mYWOgooNw: "framer-v-1x55ztc",
	nfgIbSqZH: "framer-v-jfbngd",
	Xh_OlxVRD: "framer-v-11bjff6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "Xh_OlxVRD",
	Disabled: "mFU1YIo0W",
	Error: "mYWOgooNw",
	Loading: "i5DA3SvqK",
	Success: "nfgIbSqZH",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Xh_OlxVRD",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Xh_OlxVRD",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["i5DA3SvqK", "nfgIbSqZH", "mYWOgooNw"].includes(baseVariant))
			return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-11bjff6",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"Xh_OlxVRD"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
						{...addPropertyOverrides(
							{
								"Xh_OlxVRD-hover": {
									"data-framer-name": void 0,
								},
								"Xh_OlxVRD-pressed": {
									"data-framer-name": void 0,
								},
								i5DA3SvqK: {
									"data-framer-name": "Loading",
								},
								mFU1YIo0W: {
									"data-framer-name": "Disabled",
								},
								mYWOgooNw: {
									"data-framer-name": "Error",
								},
								nfgIbSqZH: {
									"data-framer-name": "Success",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1o6w7gl"}
							data-border={true}
							data-framer-name={"White - Big email"}
							layoutDependency={layoutDependency}
							layoutId={"CrEFB8eLg"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(255, 255, 255, 0.3)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
								borderBottomLeftRadius: 32,
								borderBottomRightRadius: 32,
								borderTopLeftRadius: 32,
								borderTopRightRadius: 32,
								boxShadow: "0px 2px 1px -1px rgba(0, 0, 0, 0.06)",
							}}
						>
							<motion.div
								className={"framer-1j4vc88"}
								data-framer-name={"button name"}
								layoutDependency={layoutDependency}
								layoutId={"abBxVyAbE"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1yr8ul2"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"bcQXS7Tur"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
										opacity: 1,
									}}
									variants={{
										"Xh_OlxVRD-hover": {
											opacity: 1,
										},
										"Xh_OlxVRD-pressed": {
											opacity: 1,
										},
										mFU1YIo0W: {
											opacity: 0.4,
										},
										mYWOgooNw: {
											"--extracted-r6o4lv":
												"var(--token-0c5bee35-4f67-431b-8cf3-008a336c8204, rgb(245, 51, 119))",
											opacity: 1,
										},
										nfgIbSqZH: {
											opacity: 1,
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											i5DA3SvqK: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-ku03k4"}
															data-styles-preset={"hbmF94ei7"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"Loading\u2026"}
														</motion.p>
													</React.Fragment>
												),
											},
											mYWOgooNw: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-ku03k4"}
															data-styles-preset={"hbmF94ei7"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-0c5bee35-4f67-431b-8cf3-008a336c8204, rgb(245, 51, 119)))",
															}}
														>
															{"Something is wrong!"}
														</motion.p>
													</React.Fragment>
												),
											},
											nfgIbSqZH: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-ku03k4"}
															data-styles-preset={"hbmF94ei7"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"Thank you!"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-ku03k4"}
											data-styles-preset={"hbmF94ei7"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"Send Message"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-mbwaac"}
									data-framer-name={"icon"}
									layoutDependency={layoutDependency}
									layoutId={"PRxWp3EwM"}
									style={{
										backgroundColor:
											"var(--token-22a3c965-866d-4255-a6ee-dd1ecb84af84, rgb(255, 217, 0))",
										borderBottomLeftRadius: 30,
										borderBottomRightRadius: 30,
										borderTopLeftRadius: 30,
										borderTopRightRadius: 30,
									}}
									variants={{
										"Xh_OlxVRD-hover": {
											backgroundColor:
												"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
										},
										"Xh_OlxVRD-pressed": {
											backgroundColor:
												"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
										},
										mFU1YIo0W: {
											backgroundColor:
												"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
										},
									}}
								>
									<motion.div
										className={"framer-1fb794b"}
										data-framer-name={"arrow icon"}
										layoutDependency={layoutDependency}
										layoutId={"or_7NIWwR"}
										transformTemplate={transformTemplate1}
									>
										<motion.div
											className={"framer-2n9tgq"}
											layoutDependency={layoutDependency}
											layoutId={"NCmXaj9TS"}
											style={{
												backgroundColor:
													"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
												borderBottomLeftRadius: 3,
												borderBottomRightRadius: 3,
												borderTopLeftRadius: 3,
												borderTopRightRadius: 3,
											}}
										/>
										<motion.div
											className={"framer-1nub5kf"}
											layoutDependency={layoutDependency}
											layoutId={"W74kfeFo0"}
											style={{
												backgroundColor:
													"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
												borderBottomLeftRadius: 10,
												borderTopLeftRadius: 10,
												borderTopRightRadius: 2,
												rotate: 45,
											}}
										/>
										<motion.div
											className={"framer-1oxyeh0"}
											layoutDependency={layoutDependency}
											layoutId={"dqWDOtX6N"}
											style={{
												backgroundColor:
													"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
												borderBottomLeftRadius: 10,
												borderBottomRightRadius: 2,
												borderTopLeftRadius: 10,
												rotate: -45,
											}}
										/>
									</motion.div>
								</motion.div>
							)}
						</motion.div>
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ycJBS.framer-1cn0tye, .framer-ycJBS .framer-1cn0tye { display: block; }",
	".framer-ycJBS.framer-11bjff6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 198px; }",
	".framer-ycJBS .framer-1o6w7gl { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: 52px; justify-content: space-between; overflow: visible; padding: 0px 9px 0px 22px; position: relative; width: 1px; }",
	".framer-ycJBS .framer-1j4vc88 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 12px 0px 0px; position: relative; width: min-content; }",
	".framer-ycJBS .framer-1yr8ul2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-ycJBS .framer-mbwaac { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 32px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 32px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ycJBS .framer-1fb794b { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; min-height: 20px; min-width: 20px; overflow: visible; padding: 0px; position: absolute; top: 50%; width: min-content; z-index: 1; }",
	".framer-ycJBS .framer-2n9tgq { flex: none; height: 2px; left: calc(50.00000000000002% - 15px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 15px; z-index: 1; }",
	".framer-ycJBS .framer-1nub5kf { flex: none; height: 2px; overflow: visible; position: absolute; right: 2px; top: 6px; width: 9px; z-index: 1; }",
	".framer-ycJBS .framer-1oxyeh0 { bottom: 6px; flex: none; height: 2px; overflow: visible; position: absolute; right: 2px; width: 9px; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ycJBS.framer-11bjff6, .framer-ycJBS .framer-1j4vc88, .framer-ycJBS .framer-mbwaac, .framer-ycJBS .framer-1fb794b { gap: 0px; } .framer-ycJBS.framer-11bjff6 > *, .framer-ycJBS .framer-1fb794b > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-ycJBS.framer-11bjff6 > :first-child, .framer-ycJBS .framer-1j4vc88 > :first-child, .framer-ycJBS .framer-mbwaac > :first-child, .framer-ycJBS .framer-1fb794b > :first-child { margin-left: 0px; } .framer-ycJBS.framer-11bjff6 > :last-child, .framer-ycJBS .framer-1j4vc88 > :last-child, .framer-ycJBS .framer-mbwaac > :last-child, .framer-ycJBS .framer-1fb794b > :last-child { margin-right: 0px; } .framer-ycJBS .framer-1j4vc88 > *, .framer-ycJBS .framer-mbwaac > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	".framer-ycJBS.framer-v-132odtq.framer-11bjff6, .framer-ycJBS.framer-v-10qbtw2.framer-11bjff6, .framer-ycJBS.framer-v-jfbngd.framer-11bjff6, .framer-ycJBS.framer-v-1x55ztc.framer-11bjff6 { cursor: unset; }",
	".framer-ycJBS.framer-v-132odtq .framer-1o6w7gl, .framer-ycJBS.framer-v-jfbngd .framer-1o6w7gl, .framer-ycJBS.framer-v-1x55ztc .framer-1o6w7gl { gap: 0px; justify-content: center; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ycJBS.framer-v-132odtq .framer-1o6w7gl { gap: 0px; } .framer-ycJBS.framer-v-132odtq .framer-1o6w7gl > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-ycJBS.framer-v-132odtq .framer-1o6w7gl > :first-child { margin-left: 0px; } .framer-ycJBS.framer-v-132odtq .framer-1o6w7gl > :last-child { margin-right: 0px; } }",
	".framer-ycJBS.framer-v-jfbngd .framer-1yr8ul2 { order: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ycJBS.framer-v-jfbngd .framer-1o6w7gl { gap: 0px; } .framer-ycJBS.framer-v-jfbngd .framer-1o6w7gl > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-ycJBS.framer-v-jfbngd .framer-1o6w7gl > :first-child { margin-left: 0px; } .framer-ycJBS.framer-v-jfbngd .framer-1o6w7gl > :last-child { margin-right: 0px; } }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ycJBS.framer-v-1x55ztc .framer-1o6w7gl { gap: 0px; } .framer-ycJBS.framer-v-1x55ztc .framer-1o6w7gl > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-ycJBS.framer-v-1x55ztc .framer-1o6w7gl > :first-child { margin-left: 0px; } .framer-ycJBS.framer-v-1x55ztc .framer-1o6w7gl > :last-child { margin-right: 0px; } }",
	".framer-ycJBS.framer-v-11bjff6.hover .framer-2n9tgq, .framer-ycJBS.framer-v-11bjff6.pressed .framer-2n9tgq { left: -7px; width: 25px; }",
	".framer-ycJBS.framer-v-11bjff6.hover .framer-1nub5kf, .framer-ycJBS.framer-v-11bjff6.pressed .framer-1nub5kf { right: 2px; top: 7px; width: 7px; }",
	".framer-ycJBS.framer-v-11bjff6.hover .framer-1oxyeh0, .framer-ycJBS.framer-v-11bjff6.pressed .framer-1oxyeh0 { bottom: 7px; right: 2px; width: 7px; }",
	...css,
	'.framer-ycJBS[data-border="true"]::after, .framer-ycJBS [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramermLgXWeWm5 = withCSS(Component, css2, "framer-ycJBS");
var stdin_default = FramermLgXWeWm5;
FramermLgXWeWm5.displayName = "Button for form";
FramermLgXWeWm5.defaultProps = {
	height: 52,
	width: 198,
};
addPropertyControls(FramermLgXWeWm5, {
	variant: {
		options: ["Xh_OlxVRD", "i5DA3SvqK", "mFU1YIo0W", "nfgIbSqZH", "mYWOgooNw"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramermLgXWeWm5,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-for-form
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonForFormFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_for_form_default = ComponentWithRoot;
export { button_for_form_default as default };
