// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * year?: string // Year
 * descript?: string // Descript
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-J62DXVUY.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-56BU4VVF.js";
import { className, css, fonts } from "./chunks/chunk-FRA4GJSE.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:event-item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/yaHxKnEh0joie6q62HyA/KD9VFNff4FddWyBCdLZt/mYhH80gWS.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["PZBlTmX2e", "rq6RPKJ12", "dWwWxNcRL"];
var serializationHash = "framer-wPGhh";
var variantClassNames = {
	dWwWxNcRL: "framer-v-j7y0c1",
	PZBlTmX2e: "framer-v-1dsar57",
	rq6RPKJ12: "framer-v-wzu0rz",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "PZBlTmX2e",
	Phone: "dWwWxNcRL",
	Tablet: "rq6RPKJ12",
};
var getProps = ({ descript, height, id, width, year, ...props }) => {
	return {
		...props,
		hK4T_MiuF: year ?? props.hK4T_MiuF ?? "1900",
		jsnq39o28: descript ?? props.jsnq39o28 ?? "Sometext",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "PZBlTmX2e",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		hK4T_MiuF,
		jsnq39o28,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "PZBlTmX2e",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1dsar57",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"PZBlTmX2e"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								dWwWxNcRL: {
									"data-framer-name": "Phone",
								},
								rq6RPKJ12: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-mwzqkx"}
							data-framer-name={"event"}
							layoutDependency={layoutDependency}
							layoutId={"Kb6SXPbiO"}
						>
							<motion.div
								className={"framer-1x7s65m"}
								data-framer-name={"year"}
								layoutDependency={layoutDependency}
								layoutId={"NCPwIdUEN"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1qim8rf"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"sngZxr0qS"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={hK4T_MiuF}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											dWwWxNcRL: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6itgtr"}
															data-styles-preset={"FZGedFAXG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"1900"}
														</motion.p>
													</React.Fragment>
												),
											},
											rq6RPKJ12: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6itgtr"}
															data-styles-preset={"FZGedFAXG"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"1900"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1p2lctb"}
											data-styles-preset={"oGaRRKTWQ"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"1900"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1ba9ydq"}
								data-framer-name={"descr"}
								layoutDependency={layoutDependency}
								layoutId={"zemJtuJto"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-8g6quc"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"YIm4zNNMR"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={jsnq39o28}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-5vtfax"}
											data-styles-preset={"xHNsUW18k"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"Sometext"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-1je8s31"}
							data-framer-name={"line"}
							layoutDependency={layoutDependency}
							layoutId={"iG4fJa2Qg"}
							style={{
								backgroundColor:
									"var(--token-544f42e5-41ad-4707-98e6-458c7730fe9a, rgb(214, 219, 220))",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-wPGhh.framer-1q7km8, .framer-wPGhh .framer-1q7km8 { display: block; }",
	".framer-wPGhh.framer-1dsar57 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 940px; }",
	".framer-wPGhh .framer-mwzqkx { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 18px 0px 0px; position: relative; width: 100%; }",
	".framer-wPGhh .framer-1x7s65m { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 0px 0px; position: relative; width: 1px; }",
	".framer-wPGhh .framer-1qim8rf { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-wPGhh .framer-1ba9ydq { align-content: center; align-items: center; display: flex; flex: 3 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 0px 0px; position: relative; width: 1px; }",
	".framer-wPGhh .framer-8g6quc { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-wPGhh .framer-1je8s31 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-wPGhh.framer-1dsar57, .framer-wPGhh .framer-mwzqkx, .framer-wPGhh .framer-1x7s65m, .framer-wPGhh .framer-1ba9ydq, .framer-wPGhh .framer-1je8s31 { gap: 0px; } .framer-wPGhh.framer-1dsar57 > * { margin: 0px; margin-bottom: calc(36px / 2); margin-top: calc(36px / 2); } .framer-wPGhh.framer-1dsar57 > :first-child, .framer-wPGhh .framer-1ba9ydq > :first-child { margin-top: 0px; } .framer-wPGhh.framer-1dsar57 > :last-child, .framer-wPGhh .framer-1ba9ydq > :last-child { margin-bottom: 0px; } .framer-wPGhh .framer-mwzqkx > * { margin: 0px; margin-left: calc(30px / 2); margin-right: calc(30px / 2); } .framer-wPGhh .framer-mwzqkx > :first-child, .framer-wPGhh .framer-1x7s65m > :first-child, .framer-wPGhh .framer-1je8s31 > :first-child { margin-left: 0px; } .framer-wPGhh .framer-mwzqkx > :last-child, .framer-wPGhh .framer-1x7s65m > :last-child, .framer-wPGhh .framer-1je8s31 > :last-child { margin-right: 0px; } .framer-wPGhh .framer-1x7s65m > *, .framer-wPGhh .framer-1je8s31 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-wPGhh .framer-1ba9ydq > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	".framer-wPGhh.framer-v-wzu0rz.framer-1dsar57 { width: 746px; }",
	".framer-wPGhh.framer-v-j7y0c1.framer-1dsar57 { width: 326px; }",
	".framer-wPGhh.framer-v-j7y0c1 .framer-mwzqkx { flex-direction: column; gap: 16px; padding: 0px; }",
	".framer-wPGhh.framer-v-j7y0c1 .framer-1x7s65m { flex: none; width: 100%; }",
	".framer-wPGhh.framer-v-j7y0c1 .framer-1ba9ydq { flex: none; padding: 0px; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-wPGhh.framer-v-j7y0c1 .framer-mwzqkx { gap: 0px; } .framer-wPGhh.framer-v-j7y0c1 .framer-mwzqkx > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-wPGhh.framer-v-j7y0c1 .framer-mwzqkx > :first-child { margin-top: 0px; } .framer-wPGhh.framer-v-j7y0c1 .framer-mwzqkx > :last-child { margin-bottom: 0px; } }",
	...css3,
	...css2,
	...css,
];
var FramermYhH80gWS = withCSS(Component, css4, "framer-wPGhh");
var stdin_default = FramermYhH80gWS;
FramermYhH80gWS.displayName = "Event item";
FramermYhH80gWS.defaultProps = {
	height: 85,
	width: 940,
};
addPropertyControls(FramermYhH80gWS, {
	variant: {
		options: ["PZBlTmX2e", "rq6RPKJ12", "dWwWxNcRL"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	hK4T_MiuF: {
		defaultValue: "1900",
		displayTextArea: false,
		title: "Year",
		type: ControlType.String,
	},
	jsnq39o28: {
		defaultValue: "Sometext",
		displayTextArea: false,
		title: "Descript",
		type: ControlType.String,
	},
});
addFonts(
	FramermYhH80gWS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:event-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders EventItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var event_item_default = ComponentWithRoot;
export { event_item_default as default };
