// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Small desktop' | 'Tablet' | 'Phone' | 'Desktop - hov' // Variant
 * menutext?: string // Menutext
 * menu?: string // Menu
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-A7FSNTZK.js";
import { className, css, fonts } from "./chunks/chunk-FXKGCX3E.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-OMUMNNEF.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:menitem-footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3NWsCeestpcmVbLVdn63/e1ldJo0dudiheu1dKK04/dGh6CYNY3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = [
	"Cwidx6C5E",
	"UQjOUTvwd",
	"SRNZR5HBe",
	"WRx9RPxge",
	"bCjwj_eaS",
];
var serializationHash = "framer-V9blg";
var variantClassNames = {
	bCjwj_eaS: "framer-v-1rfvfxr",
	Cwidx6C5E: "framer-v-12ex1zr",
	SRNZR5HBe: "framer-v-qq23qo",
	UQjOUTvwd: "framer-v-1frrzkk",
	WRx9RPxge: "framer-v-mi4j1d",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0,
	delay: 0,
	duration: 0.3,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop - hov": "bCjwj_eaS",
	"Small desktop": "UQjOUTvwd",
	Desktop: "Cwidx6C5E",
	Phone: "WRx9RPxge",
	Tablet: "SRNZR5HBe",
};
var getProps = ({ height, id, menu, menutext, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Cwidx6C5E",
		Wuvq9HOvk: menutext ?? props.Wuvq9HOvk ?? "Item",
		x9XC9R4Ng: menu ?? props.x9XC9R4Ng,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		Wuvq9HOvk,
		x9XC9R4Ng,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Cwidx6C5E",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterh9kq8v = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("bCjwj_eaS");
	});
	const onMouseLeave1o29tvy = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("Cwidx6C5E");
	});
	const sharedStyleClassNames = [className3, className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-12ex1zr",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"Cwidx6C5E"}
						onMouseEnter={onMouseEnterh9kq8v}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								bCjwj_eaS: {
									"data-framer-name": "Desktop - hov",
									onMouseLeave: onMouseLeave1o29tvy,
								},
								SRNZR5HBe: {
									"data-framer-name": "Tablet",
									"data-highlight": void 0,
									onMouseEnter: void 0,
								},
								UQjOUTvwd: {
									"data-framer-name": "Small desktop",
								},
								WRx9RPxge: {
									"data-framer-name": "Phone",
									"data-highlight": void 0,
									onMouseEnter: void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-hpbdb6"}
							data-framer-name={"container"}
							layoutDependency={layoutDependency}
							layoutId={"uDPjIZ6oy"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1fbl97r"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ZCBKQB6Q3"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={Wuvq9HOvk}
								transformTemplate={transformTemplate1}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										bCjwj_eaS: {
											transformTemplate: void 0,
										},
										WRx9RPxge: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-w9yjg9"}
														data-styles-preset={"CJkhvaLRU"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))",
														}}
													>
														<Link
															href={x9XC9R4Ng}
															motionChild={true}
															nodeId={"ZCBKQB6Q3"}
															openInNewTab={false}
															scopeId={"dGh6CYNY3"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1asbn7t"}
																data-styles-preset={"huMC_BFai"}
															>
																{"Item"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-y3uj2z"}
										data-styles-preset={"WVsr1TlA5"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))",
										}}
									>
										<Link
											href={x9XC9R4Ng}
											motionChild={true}
											nodeId={"ZCBKQB6Q3"}
											openInNewTab={false}
											scopeId={"dGh6CYNY3"}
											smoothScroll={false}
										>
											<motion.a
												className={"framer-styles-preset-1asbn7t"}
												data-styles-preset={"huMC_BFai"}
											>
												{"Item"}
											</motion.a>
										</Link>
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-pn5uv6"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"hxwdSNh4N"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={Wuvq9HOvk}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										bCjwj_eaS: {
											transformTemplate: transformTemplate1,
										},
										WRx9RPxge: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-w9yjg9"}
														data-styles-preset={"CJkhvaLRU"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))",
														}}
													>
														<Link
															href={x9XC9R4Ng}
															motionChild={true}
															nodeId={"hxwdSNh4N"}
															openInNewTab={false}
															scopeId={"dGh6CYNY3"}
															smoothScroll={false}
														>
															<motion.a
																className={"framer-styles-preset-1asbn7t"}
																data-styles-preset={"huMC_BFai"}
															>
																{"Item"}
															</motion.a>
														</Link>
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-y3uj2z"}
										data-styles-preset={"WVsr1TlA5"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))",
										}}
									>
										<Link
											href={x9XC9R4Ng}
											motionChild={true}
											nodeId={"hxwdSNh4N"}
											openInNewTab={false}
											scopeId={"dGh6CYNY3"}
											smoothScroll={false}
										>
											<motion.a
												className={"framer-styles-preset-1asbn7t"}
												data-styles-preset={"huMC_BFai"}
											>
												{"Item"}
											</motion.a>
										</Link>
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-V9blg.framer-omlo4b, .framer-V9blg .framer-omlo4b { display: block; }",
	".framer-V9blg.framer-12ex1zr { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 317px; }",
	".framer-V9blg .framer-hpbdb6 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 46px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-V9blg .framer-1fbl97r { flex: none; height: auto; position: absolute; right: 0px; top: 50%; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-V9blg .framer-pn5uv6 { flex: none; height: auto; position: absolute; right: 0px; top: -42px; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-V9blg.framer-v-1frrzkk.framer-12ex1zr { width: 259px; }",
	".framer-V9blg.framer-v-qq23qo.framer-12ex1zr { width: 224px; }",
	".framer-V9blg.framer-v-mi4j1d.framer-12ex1zr { height: 40px; width: 148px; }",
	".framer-V9blg.framer-v-1rfvfxr.framer-12ex1zr { width: 317px; }",
	".framer-V9blg.framer-v-1rfvfxr .framer-1fbl97r { bottom: -40px; top: unset; }",
	".framer-V9blg.framer-v-1rfvfxr .framer-pn5uv6 { top: 50%; }",
	...css3,
	...css2,
	...css,
];
var FramerdGh6CYNY3 = withCSS(Component, css4, "framer-V9blg");
var stdin_default = FramerdGh6CYNY3;
FramerdGh6CYNY3.displayName = "Menitem footer";
FramerdGh6CYNY3.defaultProps = {
	height: 46,
	width: 316.5,
};
addPropertyControls(FramerdGh6CYNY3, {
	variant: {
		options: ["Cwidx6C5E", "UQjOUTvwd", "SRNZR5HBe", "WRx9RPxge", "bCjwj_eaS"],
		optionTitles: [
			"Desktop",
			"Small desktop",
			"Tablet",
			"Phone",
			"Desktop - hov",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	Wuvq9HOvk: {
		defaultValue: "Item",
		displayTextArea: false,
		title: "Menutext",
		type: ControlType.String,
	},
	x9XC9R4Ng: {
		title: "Menu",
		type: ControlType.Link,
	},
});
addFonts(
	FramerdGh6CYNY3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:menitem-footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MenitemFooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var menitem_footer_default = ComponentWithRoot;
export { menitem_footer_default as default };
