// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Small desktop' | 'Tablet' | 'Phone' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:moment-long
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/cRwzNDuQlsFAmZ957kQn/ZSdDfHjGUyh3eA1ToEPl/zoM_e2RL8.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["AemDr3mcU", "KL665sTgB", "Yzcww_SqP", "lXwC1b3ZG"];
var serializationHash = "framer-Uef59";
var variantClassNames = {
	AemDr3mcU: "framer-v-12kt906",
	KL665sTgB: "framer-v-1ybtd9c",
	lXwC1b3ZG: "framer-v-xgfrla",
	Yzcww_SqP: "framer-v-ii77h9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Small desktop": "KL665sTgB",
	Desktop: "AemDr3mcU",
	Phone: "lXwC1b3ZG",
	Tablet: "Yzcww_SqP",
};
var getProps = ({ height, id, image, width, ...props }) => {
	return {
		...props,
		doDK0MdAy: image ?? props.doDK0MdAy,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "AemDr3mcU",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, doDK0MdAy, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "AemDr3mcU",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image
						{...restProps}
						{...gestureHandlers}
						background={{
							alt: "",
							fit: "fill",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							sizes: componentViewport?.width || "100vw",
							...toResponsiveImage(doDK0MdAy),
						}}
						className={cx(
							scopingClassNames,
							"framer-12kt906",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"AemDr3mcU"}
						ref={ref ?? ref1}
						style={{
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
						{...addPropertyOverrides(
							{
								KL665sTgB: {
									"data-framer-name": "Small desktop",
								},
								lXwC1b3ZG: {
									"data-framer-name": "Phone",
								},
								Yzcww_SqP: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					/>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Uef59.framer-11nbo7e, .framer-Uef59 .framer-11nbo7e { display: block; }",
	".framer-Uef59.framer-12kt906 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 201px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 432px; will-change: var(--framer-will-change-override, transform); }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Uef59.framer-12kt906 { gap: 0px; } .framer-Uef59.framer-12kt906 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-Uef59.framer-12kt906 > :first-child { margin-top: 0px; } .framer-Uef59.framer-12kt906 > :last-child { margin-bottom: 0px; } }",
	".framer-Uef59.framer-v-1ybtd9c.framer-12kt906 { aspect-ratio: 2.154040404040404 / 1; height: var(--framer-aspect-ratio-supported, 166px); width: 356px; }",
	".framer-Uef59.framer-v-ii77h9.framer-12kt906 { aspect-ratio: 2.154040404040404 / 1; height: var(--framer-aspect-ratio-supported, 166px); width: 358px; }",
	".framer-Uef59.framer-v-xgfrla.framer-12kt906 { height: 151px; width: 326px; }",
];
var FramerzoM_e2RL8 = withCSS(Component, css, "framer-Uef59");
var stdin_default = FramerzoM_e2RL8;
FramerzoM_e2RL8.displayName = "Moment long";
FramerzoM_e2RL8.defaultProps = {
	height: 200.5,
	width: 432,
};
addPropertyControls(FramerzoM_e2RL8, {
	variant: {
		options: ["AemDr3mcU", "KL665sTgB", "Yzcww_SqP", "lXwC1b3ZG"],
		optionTitles: ["Desktop", "Small desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	doDK0MdAy: {
		description: "Change the image",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerzoM_e2RL8,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:moment-long
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MomentLongFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var moment_long_default = ComponentWithRoot;
export { moment_long_default as default };
