// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Small desktop' | 'Tablet' | 'Phone' // Variant
 * number?: string // Number
 * description?: string // Description
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-56BU4VVF.js";
import { className, css, fonts } from "./chunks/chunk-AJZAESD4.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FRA4GJSE.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:other
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/cmzL8CUY8O9GLrhG2xsd/RzcHeEoR8cd6nVmjs0sZ/leKFG_qki.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/Tz3GPfZoWwQvUrqArEbM/KMuPcyId6T2dgjzOWBFx/otU2oM7ah.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter-Medium",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-MediumItalic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/khkJkwSL66WFg8SX6Wa726c.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/0E7IMbDzcGABpBwwqNEt60wU0w.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NTJ0nQgIF0gcDelS14zQ9NR9Q.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/QrcNhgEPfRl0LS8qz5Ln8olanl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JEXmejW8mXOYMtt0hyRg811kHac.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ksvR4VsLksjpSwnC2fPgHRNMw.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/uy9s0iWuxiNnVt8EpTI3gzohpwo.woff2",
				weight: "500",
			},
		],
	},
];
var css4 = [
	'.framer-2aR3R .framer-styles-preset-im7hx3:not(.rich-text-wrapper), .framer-2aR3R .framer-styles-preset-im7hx3.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 42px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.05em; --framer-line-height: 38px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className4 = "framer-2aR3R";

// /:https://framerusercontent.com/modules/cmzL8CUY8O9GLrhG2xsd/RzcHeEoR8cd6nVmjs0sZ/leKFG_qki.js
var cycleOrder = ["YoOKCosVq", "An7HUBzpk", "LRL4scrzm", "GgnmUwinp"];
var serializationHash = "framer-ZaLMW";
var variantClassNames = {
	An7HUBzpk: "framer-v-1a7rx2o",
	GgnmUwinp: "framer-v-mm4pgj",
	LRL4scrzm: "framer-v-1bzophs",
	YoOKCosVq: "framer-v-4p6c4h",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Small desktop": "An7HUBzpk",
	Desktop: "YoOKCosVq",
	Phone: "GgnmUwinp",
	Tablet: "LRL4scrzm",
};
var getProps = ({ description, height, id, number, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "YoOKCosVq",
		xd5sp2Cj_: description ?? props.xd5sp2Cj_ ?? "Description",
		YhCFg6LMz: number ?? props.YhCFg6LMz ?? "000",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		YhCFg6LMz,
		xd5sp2Cj_,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "YoOKCosVq",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className4, className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["LRL4scrzm", "GgnmUwinp"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-4p6c4h",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"YoOKCosVq"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "2px",
							"--border-color": "rgba(130, 132, 135, 0.33)",
							"--border-left-width": "2px",
							"--border-right-width": "2px",
							"--border-style": "dashed",
							"--border-top-width": "2px",
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
						{...addPropertyOverrides(
							{
								An7HUBzpk: {
									"data-framer-name": "Small desktop",
								},
								GgnmUwinp: {
									"data-framer-name": "Phone",
								},
								LRL4scrzm: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-nyz27y"}
							data-framer-name={"Rectangle 37"}
							layoutDependency={layoutDependency}
							layoutId={"jwnHnxiux"}
							style={{
								backgroundColor: "rgb(241, 241, 241)",
							}}
						/>
						<motion.div
							className={"framer-17n352q"}
							data-framer-name={"numblock"}
							layoutDependency={layoutDependency}
							layoutId={"qVjfIkyE_"}
						>
							<motion.div
								className={"framer-nb4fvl"}
								data-framer-name={"number"}
								layoutDependency={layoutDependency}
								layoutId={"dLW_FM2hd"}
							>
								{isDisplayed() && (
									<motion.div
										className={"framer-nvkdd"}
										data-framer-name={"-gap-"}
										layoutDependency={layoutDependency}
										layoutId={"xpd5nop22"}
									/>
								)}
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ehobx2"}
									data-framer-name={"50"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Mkv4cmTpS"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={YhCFg6LMz}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											An7HUBzpk: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
																"--framer-font-family":
																	'"Inter", "Inter Placeholder", sans-serif',
																"--framer-font-size": "50px",
																"--framer-font-weight": "600",
																"--framer-letter-spacing": "-0.05em",
																"--framer-line-height": "48px",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"000"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-SemiBold"],
											},
											GgnmUwinp: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
																"--framer-font-family":
																	'"Inter", "Inter Placeholder", sans-serif',
																"--framer-font-size": "48px",
																"--framer-font-weight": "600",
																"--framer-letter-spacing": "-0.05em",
																"--framer-line-height": "48px",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"000"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-SemiBold"],
											},
											LRL4scrzm: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
																"--framer-font-family":
																	'"Inter", "Inter Placeholder", sans-serif',
																"--framer-font-size": "60px",
																"--framer-font-weight": "600",
																"--framer-letter-spacing": "-0.05em",
																"--framer-line-height": "48px",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"000"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-SemiBold"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1p2lctb"}
											data-styles-preset={"oGaRRKTWQ"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"000"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-exz1lk"}
									data-framer-name={"+"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lUE_HVg0h"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											An7HUBzpk: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "SW50ZXItTWVkaXVt",
																"--framer-font-family":
																	'"Inter", "Inter Placeholder", sans-serif',
																"--framer-font-size": "32px",
																"--framer-font-weight": "500",
																"--framer-letter-spacing": "-0.02em",
																"--framer-line-height": "16px",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"+"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-Medium"],
											},
											GgnmUwinp: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "SW50ZXItTWVkaXVt",
																"--framer-font-family":
																	'"Inter", "Inter Placeholder", sans-serif',
																"--framer-font-size": "30px",
																"--framer-font-weight": "500",
																"--framer-letter-spacing": "-0.02em",
																"--framer-line-height": "16px",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"+"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-Medium"],
											},
											LRL4scrzm: {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "SW50ZXItTWVkaXVt",
																"--framer-font-family":
																	'"Inter", "Inter Placeholder", sans-serif',
																"--framer-font-size": "38px",
																"--framer-font-weight": "500",
																"--framer-letter-spacing": "-0.02em",
																"--framer-line-height": "16px",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"+"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-Medium"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-im7hx3"}
											data-styles-preset={"otU2oM7ah"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"+"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1y53qjf"}
								data-framer-name={"message"}
								layoutDependency={layoutDependency}
								layoutId={"GP8KO5NhL"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1jpw639"}
									data-framer-name={"People in business"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"g1hPSTuAy"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={xd5sp2Cj_}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											GgnmUwinp: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1xoeoxz"}
															data-styles-preset={"cD0evZgOT"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
															}}
														>
															{"Description"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-5vtfax"}
											data-styles-preset={"xHNsUW18k"}
											style={{
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
											}}
										>
											{"Description"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ZaLMW.framer-ae9011, .framer-ZaLMW .framer-ae9011 { display: block; }",
	".framer-ZaLMW.framer-4p6c4h { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 200px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 206px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ZaLMW .framer-nyz27y { flex: none; height: 118px; left: calc(50.00000000000002% - 100.97087378640776% / 2); position: absolute; top: calc(49.87531172069828% - 118px / 2); width: 101%; z-index: 1; }",
	".framer-ZaLMW .framer-17n352q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 12px 0px 12px; position: relative; width: 100%; }",
	".framer-ZaLMW .framer-nb4fvl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-ZaLMW .framer-nvkdd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; min-height: 16px; overflow: hidden; padding: 0px; position: relative; width: 14%; }",
	".framer-ZaLMW .framer-ehobx2, .framer-ZaLMW .framer-exz1lk { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-ZaLMW .framer-1y53qjf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZaLMW .framer-1jpw639 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ZaLMW.framer-4p6c4h, .framer-ZaLMW .framer-17n352q, .framer-ZaLMW .framer-nb4fvl, .framer-ZaLMW .framer-nvkdd, .framer-ZaLMW .framer-1y53qjf { gap: 0px; } .framer-ZaLMW.framer-4p6c4h > *, .framer-ZaLMW .framer-1y53qjf > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-ZaLMW.framer-4p6c4h > :first-child, .framer-ZaLMW .framer-17n352q > :first-child, .framer-ZaLMW .framer-nvkdd > :first-child, .framer-ZaLMW .framer-1y53qjf > :first-child { margin-top: 0px; } .framer-ZaLMW.framer-4p6c4h > :last-child, .framer-ZaLMW .framer-17n352q > :last-child, .framer-ZaLMW .framer-nvkdd > :last-child, .framer-ZaLMW .framer-1y53qjf > :last-child { margin-bottom: 0px; } .framer-ZaLMW .framer-17n352q > * { margin: 0px; margin-bottom: calc(6px / 2); margin-top: calc(6px / 2); } .framer-ZaLMW .framer-nb4fvl > * { margin: 0px; margin-left: calc(2px / 2); margin-right: calc(2px / 2); } .framer-ZaLMW .framer-nb4fvl > :first-child { margin-left: 0px; } .framer-ZaLMW .framer-nb4fvl > :last-child { margin-right: 0px; } .framer-ZaLMW .framer-nvkdd > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	".framer-ZaLMW.framer-v-1a7rx2o.framer-4p6c4h { aspect-ratio: 1.0277777777777777 / 1; height: var(--framer-aspect-ratio-supported, 164px); width: 168px; }",
	".framer-ZaLMW.framer-v-1a7rx2o .framer-nyz27y { height: 110px; left: calc(50.00000000000002% - 101.19047619047619% / 2); top: calc(48.92966360856271% - 110px / 2); width: 101%; }",
	".framer-ZaLMW.framer-v-1bzophs.framer-4p6c4h { aspect-ratio: 1.0277777777777777 / 1; height: var(--framer-aspect-ratio-supported, 223px); width: 229px; }",
	".framer-ZaLMW.framer-v-1bzophs .framer-nyz27y { height: 143px; left: calc(49.78165938864631% - 100.87336244541486% / 2); top: calc(49.327354260089706% - 143px / 2); width: 101%; }",
	".framer-ZaLMW.framer-v-mm4pgj.framer-4p6c4h { aspect-ratio: 1.0277777777777777 / 1; height: var(--framer-aspect-ratio-supported, 144px); width: 148px; }",
	".framer-ZaLMW.framer-v-mm4pgj .framer-nyz27y { height: 105px; left: calc(50.00000000000002% - 101.35135135135135% / 2); top: calc(49.30555555555558% - 105px / 2); width: 101%; }",
	...css3,
	...css4,
	...css2,
	...css,
	'.framer-ZaLMW[data-border="true"]::after, .framer-ZaLMW [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerleKFG_qki = withCSS(Component, css5, "framer-ZaLMW");
var stdin_default = FramerleKFG_qki;
FramerleKFG_qki.displayName = "Other";
FramerleKFG_qki.defaultProps = {
	height: 200.5,
	width: 206,
};
addPropertyControls(FramerleKFG_qki, {
	variant: {
		options: ["YoOKCosVq", "An7HUBzpk", "LRL4scrzm", "GgnmUwinp"],
		optionTitles: ["Desktop", "Small desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	YhCFg6LMz: {
		defaultValue: "000",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
	xd5sp2Cj_: {
		defaultValue: "Description",
		description: "Change the number and the sign",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
});
addFonts(
	FramerleKFG_qki,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:other
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders OtherFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var other_default = ComponentWithRoot;
export { other_default as default };
