// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Small desktop' | 'Tablet' | 'Phone' // Variant
 * start№?: number // Start №
 * end№?: number // End №
 * speedMs?: number // Speed Ms
 * header?: string // Header
 * description?: string // Description
 * image1?: {src: string, srcSet?: string, alt?: string} // Image1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image3
}} Props

 */
import { Counter } from "./chunks/chunk-E2DAPCSK.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-AJZAESD4.js";
import { className, css, fonts } from "./chunks/chunk-HOYSAFYX.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-FRA4GJSE.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:our-num-square
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lk27kjs88NlV6PATtIVZ/VfmybfmmDQzsCtnjXqzy/I1mPl4_ty.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CounterFonts = getFonts(Counter);
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["zzK1rfvzI", "mISiWvsSQ", "hSwbe9Wmk", "Ae18_EWAB"];
var serializationHash = "framer-FEMYU";
var variantClassNames = {
	Ae18_EWAB: "framer-v-1evfmtp",
	hSwbe9Wmk: "framer-v-1hcmyjl",
	mISiWvsSQ: "framer-v-y71rnt",
	zzK1rfvzI: "framer-v-fk6d84",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 170,
	y: 0,
};
var transition2 = {
	bounce: 0.1,
	delay: 0,
	duration: 3,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 170,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Small desktop": "mISiWvsSQ",
	Desktop: "zzK1rfvzI",
	Phone: "Ae18_EWAB",
	Tablet: "hSwbe9Wmk",
};
var getProps = ({
	description,
	end,
	header,
	height,
	id,
	image1,
	image2,
	image3,
	speedMs,
	start,
	width,
	...props
}) => {
	return {
		...props,
		bILnmMv5T: speedMs ?? props.bILnmMv5T ?? 20,
		FtU0IaJku: image1 ?? props.FtU0IaJku,
		hP4Ewwxgx: image3 ?? props.hP4Ewwxgx,
		LpoIDg56M: start ?? props.LpoIDg56M,
		lUWnLMryT: description ?? props.lUWnLMryT ?? "Description",
		msEK4QV7e: header ?? props.msEK4QV7e ?? "Header",
		o4eoOKc1z: image2 ?? props.o4eoOKc1z,
		uA7lj4jBE: end ?? props.uA7lj4jBE,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zzK1rfvzI",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		LpoIDg56M,
		uA7lj4jBE,
		bILnmMv5T,
		msEK4QV7e,
		lUWnLMryT,
		FtU0IaJku,
		o4eoOKc1z,
		hP4Ewwxgx,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zzK1rfvzI",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "Ae18_EWAB") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-fk6d84",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"zzK1rfvzI"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								Ae18_EWAB: {
									"data-framer-name": "Phone",
								},
								hSwbe9Wmk: {
									"data-framer-name": "Tablet",
								},
								mISiWvsSQ: {
									"data-framer-name": "Small desktop",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1h5vf6n-container"}
								isAuthoredByUser={true}
								layoutDependency={layoutDependency}
								layoutId={"gTwVvoVWt-container"}
								nodeId={"gTwVvoVWt"}
								rendersWithMotion={true}
								scopeId={"I1mPl4_ty"}
							>
								<Counter
									end={uA7lj4jBE}
									gapSize={4}
									height={"100%"}
									id={"gTwVvoVWt"}
									layoutId={"gTwVvoVWt"}
									letterSpacing={-0.05}
									loop={false}
									restartOnViewport={false}
									selectedFont={{
										fontFamily: '"Inter", "Inter Placeholder", sans-serif',
										fontStyle: "normal",
										fontWeight: 600,
									}}
									speed={bILnmMv5T}
									start={LpoIDg56M}
									startOnViewport={true}
									textColor={
										"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))"
									}
									textSize={72}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-194kdbt"}
							data-framer-name={"container"}
							layoutDependency={layoutDependency}
							layoutId={"YJTzPqSQt"}
						>
							<motion.div
								className={"framer-1ndwah8"}
								data-framer-name={"info"}
								layoutDependency={layoutDependency}
								layoutId={"I9s2gFVhn"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ur8okq"}
									data-framer-name={"Projects are launched"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"P4qGy5mP9"}
									style={{
										"--extracted-1eung3n":
											"var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={msEK4QV7e}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											Ae18_EWAB: {
												children: (
													<React.Fragment>
														<motion.h4
															style={{
																"--font-selector": "SW50ZXItTWVkaXVt",
																"--framer-font-family":
																	'"Inter", "Inter Placeholder", sans-serif',
																"--framer-font-size": "22px",
																"--framer-font-weight": "500",
																"--framer-letter-spacing": "-0.03em",
																"--framer-line-height": "30px",
																"--framer-text-color":
																	"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
															}}
														>
															{"Header"}
														</motion.h4>
													</React.Fragment>
												),
												fonts: ["Inter-Medium"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-cgx770"}
											data-styles-preset={"bLAu95yRo"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-b58ee0c0-736b-49de-961e-77f9e9613c8d, rgb(0, 0, 0)))",
											}}
										>
											{"Header"}
										</motion.h4>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-y4jp9"}
									data-framer-name={"A lot of projects are done"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"huyxakuAF"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={lUWnLMryT}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											Ae18_EWAB: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1xoeoxz"}
															data-styles-preset={"cD0evZgOT"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
															}}
														>
															{"Description"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-5vtfax"}
											data-styles-preset={"xHNsUW18k"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-40b61429-162b-47b9-abcd-b05f9c77d6da, rgb(130, 132, 135)))",
											}}
										>
											{"Description"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-mfmhyq"}
								data-framer-name={"projectimgs"}
								layoutDependency={layoutDependency}
								layoutId={"KVwOEbWMD"}
							>
								<motion.div
									className={"framer-170ugiz"}
									data-framer-name={"block"}
									layoutDependency={layoutDependency}
									layoutId={"lSaejlEIb"}
								>
									<motion.div
										className={"framer-1y4zgv3"}
										data-framer-name={"squares"}
										layoutDependency={layoutDependency}
										layoutId={"oDteSfRQr"}
									>
										<Image
											background={{
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														86 +
														(((componentViewport?.height || 368.5) - 86 - 483) /
															2 +
															200 +
															10) +
														0 +
														178 +
														0 +
														0 +
														0,
												),
												sizes: "50px",
												...toResponsiveImage(FtU0IaJku),
											}}
											className={"framer-fl9m8w"}
											data-border={true}
											data-framer-name={"Image1"}
											layoutDependency={layoutDependency}
											layoutId={"pLjrhaC2q"}
											style={{
												"--border-bottom-width": "3px",
												"--border-color":
													"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
												"--border-left-width": "3px",
												"--border-right-width": "3px",
												"--border-style": "solid",
												"--border-top-width": "3px",
												borderBottomLeftRadius: 8,
												borderBottomRightRadius: 8,
												borderTopLeftRadius: 8,
												borderTopRightRadius: 8,
											}}
											{...addPropertyOverrides(
												{
													Ae18_EWAB: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 215.5) -
																		0 -
																		408) /
																		2 +
																		200 +
																		4) +
																	0 +
																	154 +
																	0 +
																	0 +
																	0,
															),
															sizes: "50px",
															...toResponsiveImage(FtU0IaJku),
														},
													},
													hSwbe9Wmk: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 282.5) -
																		0 -
																		483) /
																		2 +
																		200 +
																		10) +
																	0 +
																	178 +
																	0 +
																	0 +
																	0,
															),
															sizes: "50px",
															...toResponsiveImage(FtU0IaJku),
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
										<Image
											background={{
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														86 +
														(((componentViewport?.height || 368.5) - 86 - 483) /
															2 +
															200 +
															10) +
														0 +
														178 +
														0 +
														0 +
														0,
												),
												sizes: "50px",
												...toResponsiveImage(o4eoOKc1z),
											}}
											className={"framer-1bkfjv6"}
											data-border={true}
											data-framer-name={"Image2"}
											layoutDependency={layoutDependency}
											layoutId={"leUkQqv2d"}
											style={{
												"--border-bottom-width": "3px",
												"--border-color":
													"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
												"--border-left-width": "3px",
												"--border-right-width": "3px",
												"--border-style": "solid",
												"--border-top-width": "3px",
												borderBottomLeftRadius: 8,
												borderBottomRightRadius: 8,
												borderTopLeftRadius: 8,
												borderTopRightRadius: 8,
											}}
											{...addPropertyOverrides(
												{
													Ae18_EWAB: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 215.5) -
																		0 -
																		408) /
																		2 +
																		200 +
																		4) +
																	0 +
																	154 +
																	0 +
																	0 +
																	0,
															),
															sizes: "50px",
															...toResponsiveImage(o4eoOKc1z),
														},
													},
													hSwbe9Wmk: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 282.5) -
																		0 -
																		483) /
																		2 +
																		200 +
																		10) +
																	0 +
																	178 +
																	0 +
																	0 +
																	0,
															),
															sizes: "50px",
															...toResponsiveImage(o4eoOKc1z),
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
										<Image
											background={{
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														86 +
														(((componentViewport?.height || 368.5) - 86 - 483) /
															2 +
															200 +
															10) +
														0 +
														178 +
														0 +
														0 +
														0,
												),
												sizes: "50px",
												...toResponsiveImage(hP4Ewwxgx),
											}}
											className={"framer-180qgsu"}
											data-border={true}
											data-framer-name={"Image3"}
											layoutDependency={layoutDependency}
											layoutId={"u4spt6M_0"}
											style={{
												"--border-bottom-width": "3px",
												"--border-color":
													"var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241))",
												"--border-left-width": "3px",
												"--border-right-width": "3px",
												"--border-style": "solid",
												"--border-top-width": "3px",
												borderBottomLeftRadius: 10,
												borderBottomRightRadius: 10,
												borderTopLeftRadius: 10,
												borderTopRightRadius: 10,
											}}
											{...addPropertyOverrides(
												{
													Ae18_EWAB: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 215.5) -
																		0 -
																		408) /
																		2 +
																		200 +
																		4) +
																	0 +
																	154 +
																	0 +
																	0 +
																	0,
															),
															sizes: "50px",
															...toResponsiveImage(hP4Ewwxgx),
														},
													},
													hSwbe9Wmk: {
														background: {
															alt: "",
															fit: "fill",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 282.5) -
																		0 -
																		483) /
																		2 +
																		200 +
																		10) +
																	0 +
																	178 +
																	0 +
																	0 +
																	0,
															),
															sizes: "50px",
															...toResponsiveImage(hP4Ewwxgx),
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</motion.div>
									<MotionDivWithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={false}
										__framer__enter={animation}
										__framer__exit={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1knhbk2"}
										data-framer-name={"line"}
										layoutDependency={layoutDependency}
										layoutId={"IPHvfmIYj"}
										style={{
											backgroundColor:
												"var(--token-544f42e5-41ad-4707-98e6-458c7730fe9a, rgb(214, 219, 220))",
										}}
									/>
								</motion.div>
								{isDisplayed() && (
									<SVG
										className={"framer-1cbofbn"}
										data-framer-name={"decor1"}
										fill={
											'var(--token-544f42e5-41ad-4707-98e6-458c7730fe9a, rgb(214, 219, 220)) /* {"name":"Decor Grey"} */'
										}
										intrinsicHeight={90}
										intrinsicWidth={40}
										layoutDependency={layoutDependency}
										layoutId={"DR6fHOenY"}
										svg={
											'<svg width="40" height="90" viewBox="0 0 40 90" fill="none" xmlns="http://www.w3.org/2000/svg">\n<line y1="-0.5" x2="40" y2="-0.5" transform="matrix(1 -8.74228e-08 -8.74228e-08 -1 0 22)" stroke="#D6DBDC"/>\n<line x1="15.5" y1="2.18557e-08" x2="15.5" y2="90" stroke="#D6DBDC"/>\n<path fill-rule="evenodd" clip-rule="evenodd" d="M0.503906 18.949L14.5022 21.9378L8.3699 21.9378L0.503906 20.201L0.503906 18.949ZM0.503906 24.806L8.36988 23.1094L14.5039 23.1094L0.503906 26.0511L0.503906 24.806Z" fill="#D6DBDC"/>\n<path fill-rule="evenodd" clip-rule="evenodd" d="M29.5039 18.949L15.5056 21.9378L21.6379 21.9378L29.5039 20.201L29.5039 18.949ZM29.5039 24.806L21.6379 23.1094L15.5039 23.1094L29.5039 26.0511L29.5039 24.806Z" fill="#D6DBDC"/>\n</svg>\n'
										}
										withExternalLayout={true}
									/>
								)}
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-FEMYU.framer-zoa5h5, .framer-FEMYU .framer-zoa5h5 { display: block; }",
	".framer-FEMYU.framer-fk6d84 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 86px 0px 0px 0px; position: relative; width: 317px; }",
	".framer-FEMYU .framer-1h5vf6n-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-FEMYU .framer-194kdbt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-FEMYU .framer-1ndwah8 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-FEMYU .framer-ur8okq, .framer-FEMYU .framer-y4jp9 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-FEMYU .framer-mfmhyq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-FEMYU .framer-170ugiz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 45px 0px; position: relative; width: 1px; }",
	".framer-FEMYU .framer-1y4zgv3 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; min-width: 111px; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-FEMYU .framer-fl9m8w { flex: none; height: 50px; overflow: hidden; position: relative; width: 50px; will-change: var(--framer-will-change-override, transform); }",
	".framer-FEMYU .framer-1bkfjv6 { bottom: 0px; flex: none; left: 30px; overflow: hidden; position: absolute; top: 0px; width: 50px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-FEMYU .framer-180qgsu { bottom: 0px; flex: none; left: 60px; overflow: hidden; position: absolute; top: 0px; width: 50px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-FEMYU .framer-1knhbk2 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: 1px; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-FEMYU .framer-1cbofbn { flex: none; height: 90px; position: relative; width: 40px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-FEMYU.framer-fk6d84, .framer-FEMYU .framer-194kdbt, .framer-FEMYU .framer-1ndwah8, .framer-FEMYU .framer-mfmhyq, .framer-FEMYU .framer-170ugiz, .framer-FEMYU .framer-1y4zgv3 { gap: 0px; } .framer-FEMYU.framer-fk6d84 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-FEMYU.framer-fk6d84 > :first-child, .framer-FEMYU .framer-194kdbt > :first-child, .framer-FEMYU .framer-1ndwah8 > :first-child { margin-top: 0px; } .framer-FEMYU.framer-fk6d84 > :last-child, .framer-FEMYU .framer-194kdbt > :last-child, .framer-FEMYU .framer-1ndwah8 > :last-child { margin-bottom: 0px; } .framer-FEMYU .framer-194kdbt > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-FEMYU .framer-1ndwah8 > * { margin: 0px; margin-bottom: calc(4px / 2); margin-top: calc(4px / 2); } .framer-FEMYU .framer-mfmhyq > *, .framer-FEMYU .framer-170ugiz > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-FEMYU .framer-mfmhyq > :first-child, .framer-FEMYU .framer-170ugiz > :first-child, .framer-FEMYU .framer-1y4zgv3 > :first-child { margin-left: 0px; } .framer-FEMYU .framer-mfmhyq > :last-child, .framer-FEMYU .framer-170ugiz > :last-child, .framer-FEMYU .framer-1y4zgv3 > :last-child { margin-right: 0px; } .framer-FEMYU .framer-1y4zgv3 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	".framer-FEMYU.framer-v-y71rnt.framer-fk6d84 { width: 259px; }",
	".framer-FEMYU.framer-v-1hcmyjl.framer-fk6d84 { padding: 0px; width: 358px; }",
	".framer-FEMYU.framer-v-1evfmtp.framer-fk6d84 { gap: 4px; padding: 0px; width: 326px; }",
	".framer-FEMYU.framer-v-1evfmtp .framer-194kdbt { gap: 20px; }",
	".framer-FEMYU.framer-v-1evfmtp .framer-170ugiz { padding: 0px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-FEMYU.framer-v-1evfmtp.framer-fk6d84, .framer-FEMYU.framer-v-1evfmtp .framer-194kdbt { gap: 0px; } .framer-FEMYU.framer-v-1evfmtp.framer-fk6d84 > * { margin: 0px; margin-bottom: calc(4px / 2); margin-top: calc(4px / 2); } .framer-FEMYU.framer-v-1evfmtp.framer-fk6d84 > :first-child, .framer-FEMYU.framer-v-1evfmtp .framer-194kdbt > :first-child { margin-top: 0px; } .framer-FEMYU.framer-v-1evfmtp.framer-fk6d84 > :last-child, .framer-FEMYU.framer-v-1evfmtp .framer-194kdbt > :last-child { margin-bottom: 0px; } .framer-FEMYU.framer-v-1evfmtp .framer-194kdbt > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } }",
	...css,
	...css3,
	...css2,
	'.framer-FEMYU[data-border="true"]::after, .framer-FEMYU [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerI1mPl4_ty = withCSS(Component, css4, "framer-FEMYU");
var stdin_default = FramerI1mPl4_ty;
FramerI1mPl4_ty.displayName = "Our num square";
FramerI1mPl4_ty.defaultProps = {
	height: 368.5,
	width: 316.5,
};
addPropertyControls(FramerI1mPl4_ty, {
	variant: {
		options: ["zzK1rfvzI", "mISiWvsSQ", "hSwbe9Wmk", "Ae18_EWAB"],
		optionTitles: ["Desktop", "Small desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	LpoIDg56M: {
		defaultValue: 0,
		displayStepper: true,
		title: "Start \u2116",
		type: ControlType.Number,
	},
	uA7lj4jBE: {
		defaultValue: 0,
		displayStepper: true,
		title: "End \u2116",
		type: ControlType.Number,
	},
	bILnmMv5T: {
		defaultValue: 20,
		description: "Set values and loop speed",
		max: 2e3,
		min: 0,
		step: 10,
		title: "Speed Ms",
		type: ControlType.Number,
	},
	msEK4QV7e: {
		defaultValue: "Header",
		displayTextArea: false,
		title: "Header",
		type: ControlType.String,
	},
	lUWnLMryT: {
		defaultValue: "Description",
		description: "Write your info",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
	FtU0IaJku: {
		title: "Image1",
		type: ControlType.ResponsiveImage,
	},
	o4eoOKc1z: {
		title: "Image2",
		type: ControlType.ResponsiveImage,
	},
	hP4Ewwxgx: {
		title: "Image3",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerI1mPl4_ty,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
			],
		},
		...CounterFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:our-num-square
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders OurNumSquareFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var our_num_square_default = ComponentWithRoot;
export { our_num_square_default as default };
