// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4b106605c55c3c39 "Housemood (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Small desktop' | 'Tablet' | 'Phone' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * occupation?: string // Occupation
 * message?: string // Message
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-HOYSAFYX.js";
import { className, css, fonts } from "./chunks/chunk-KSCEWQHB.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-C6U7IFL3.js";
import { routes } from "./chunks/chunk-6GHPDBWQ.js";

// virtual:persona-main
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qDGWiQoSkdYIM2DlZFhV/9TJGw6vJel0rpP59SddR/AfUEtwOas.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["vbCM_3WYP", "YwTz5EsVH", "Ojz5zA52T", "uiD3Abfws"];
var serializationHash = "framer-qHLLA";
var variantClassNames = {
	Ojz5zA52T: "framer-v-1qhviuo",
	uiD3Abfws: "framer-v-1jlmx8d",
	vbCM_3WYP: "framer-v-1ags10l",
	YwTz5EsVH: "framer-v-1x40ye2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Small desktop": "YwTz5EsVH",
	Desktop: "vbCM_3WYP",
	Phone: "uiD3Abfws",
	Tablet: "Ojz5zA52T",
};
var getProps = ({
	height,
	id,
	image,
	message,
	name1,
	occupation,
	width,
	...props
}) => {
	return {
		...props,
		BczzNSyyP: message ?? props.BczzNSyyP ?? "Message",
		CJvAGb136: name1 ?? props.CJvAGb136 ?? "Name",
		E0KfMuGhw: image ?? props.E0KfMuGhw,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "vbCM_3WYP",
		xFIbgZ4Jj: occupation ?? props.xFIbgZ4Jj ?? "Occupation",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		E0KfMuGhw,
		CJvAGb136,
		xFIbgZ4Jj,
		BczzNSyyP,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "vbCM_3WYP",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image
						{...restProps}
						{...gestureHandlers}
						background={{
							alt: "",
							fit: "fill",
							loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
							sizes: componentViewport?.width || "100vw",
							...toResponsiveImage(E0KfMuGhw),
						}}
						className={cx(
							scopingClassNames,
							"framer-1ags10l",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"vbCM_3WYP"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
						variants={{
							uiD3Abfws: {
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
							},
						}}
						{...addPropertyOverrides(
							{
								Ojz5zA52T: {
									"data-framer-name": "Tablet",
								},
								uiD3Abfws: {
									"data-framer-name": "Phone",
								},
								YwTz5EsVH: {
									"data-framer-name": "Small desktop",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-gn0yya"}
							data-framer-name={"about"}
							layoutDependency={layoutDependency}
							layoutId={"ILHUnjyJT"}
						>
							<motion.div
								className={"framer-imwuq5"}
								data-framer-name={"name"}
								layoutDependency={layoutDependency}
								layoutId={"MDoufTcAQ"}
							>
								<SVG
									className={"framer-1muu0sg"}
									data-framer-name={"arrow"}
									fill={
										"var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))"
									}
									intrinsicHeight={32}
									intrinsicWidth={32}
									layoutDependency={layoutDependency}
									layoutId={"nDkz5dhdL"}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 256 256"><path d="m224.49 136.49-72 72a12 12 0 0 1-17-17L187 140H40a12 12 0 0 1 0-24h147l-51.49-51.52a12 12 0 0 1 17-17l72 72a12 12 0 0 1-.02 17.01Z"/></svg>'
									}
									withExternalLayout={true}
								/>
								<motion.div
									className={"framer-1silu3k"}
									layoutDependency={layoutDependency}
									layoutId={"dzu8c47d9"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-ie6uqz"}
										data-framer-name={"name"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"WI8zvERM_"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										text={CJvAGb136}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												uiD3Abfws: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-fgvqpk"}
																data-styles-preset={"AclTOTf8Z"}
															>
																{"Name"}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-ku03k4"}
												data-styles-preset={"hbmF94ei7"}
											>
												{"Name"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1jfmr3u"}
										data-framer-name={"occupation"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"OATW28_yu"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-801a1a18-ec2a-44b0-b58c-7538b430c2c1, rgb(241, 223, 194))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={xFIbgZ4Jj}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												uiD3Abfws: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-fgvqpk"}
																data-styles-preset={"AclTOTf8Z"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-801a1a18-ec2a-44b0-b58c-7538b430c2c1, rgb(241, 223, 194)))",
																}}
															>
																{"Occupation"}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-ku03k4"}
												data-styles-preset={"hbmF94ei7"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-801a1a18-ec2a-44b0-b58c-7538b430c2c1, rgb(241, 223, 194)))",
												}}
											>
												{"Occupation"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-awfh67"}
								data-framer-name={"slogan"}
								layoutDependency={layoutDependency}
								layoutId={"PBpE6jo48"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1rrklaj"}
									data-framer-name={
										"We are here to create space that will inspire your."
									}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"cZ8fwSF8J"}
									style={{
										"--extracted-1eung3n":
											"var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={BczzNSyyP}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											uiD3Abfws: {
												children: (
													<React.Fragment>
														<motion.h4
															style={{
																"--font-selector": "SW50ZXItTWVkaXVt",
																"--framer-font-family":
																	'"Inter", "Inter Placeholder", sans-serif',
																"--framer-font-size": "18px",
																"--framer-font-weight": "500",
																"--framer-letter-spacing": "-0.03em",
																"--framer-line-height": "24px",
																"--framer-text-color":
																	"var(--extracted-1eung3n, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))",
															}}
														>
															{"Message"}
														</motion.h4>
													</React.Fragment>
												),
												fonts: ["Inter-Medium"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-cgx770"}
											data-styles-preset={"bLAu95yRo"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))",
											}}
										>
											{"Message"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</Image>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-qHLLA.framer-18xx3gx, .framer-qHLLA .framer-18xx3gx { display: block; }",
	".framer-qHLLA.framer-1ags10l { align-content: flex-end; align-items: flex-end; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 352px; justify-content: center; overflow: hidden; padding: 0px 0px 37px 0px; position: relative; width: 531px; will-change: var(--framer-will-change-override, transform); }",
	".framer-qHLLA .framer-gn0yya { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 20px 0px 30px; position: relative; width: 1px; }",
	".framer-qHLLA .framer-imwuq5 { align-content: flex-start; align-items: flex-start; display: flex; flex: 3 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-qHLLA .framer-1muu0sg { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; z-index: 1; }",
	".framer-qHLLA .framer-1silu3k { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 40px 0px 0px; position: relative; width: 100%; }",
	".framer-qHLLA .framer-ie6uqz, .framer-qHLLA .framer-1jfmr3u { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 0; }",
	".framer-qHLLA .framer-awfh67 { align-content: flex-start; align-items: flex-start; display: flex; flex: 2 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 24px 0px 0px 0px; position: relative; width: 1px; }",
	".framer-qHLLA .framer-1rrklaj { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-qHLLA.framer-v-1x40ye2.framer-1ags10l { aspect-ratio: 1.5057471264367817 / 1; height: var(--framer-aspect-ratio-supported, 292px); width: 439px; }",
	".framer-qHLLA.framer-v-1qhviuo.framer-1ags10l { aspect-ratio: 1.5050437121721587 / 1; height: var(--framer-aspect-ratio-supported, 323px); width: 486px; }",
	".framer-qHLLA.framer-v-1jlmx8d.framer-1ags10l { aspect-ratio: 1.5050437121721587 / 1; height: var(--framer-aspect-ratio-supported, 217px); padding: 0px 0px 24px 0px; width: 326px; }",
	".framer-qHLLA.framer-v-1jlmx8d .framer-gn0yya { padding: 0px 20px 0px 20px; }",
	...css3,
	...css,
	...css2,
];
var FramerAfUEtwOas = withCSS(Component, css4, "framer-qHLLA");
var stdin_default = FramerAfUEtwOas;
FramerAfUEtwOas.displayName = "Persona main";
FramerAfUEtwOas.defaultProps = {
	height: 352,
	width: 530,
};
addPropertyControls(FramerAfUEtwOas, {
	variant: {
		options: ["vbCM_3WYP", "YwTz5EsVH", "Ojz5zA52T", "uiD3Abfws"],
		optionTitles: ["Desktop", "Small desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	E0KfMuGhw: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	CJvAGb136: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	xFIbgZ4Jj: {
		defaultValue: "Occupation",
		displayTextArea: false,
		title: "Occupation",
		type: ControlType.String,
	},
	BczzNSyyP: {
		defaultValue: "Message",
		description:
			"Place your persona image,write his name, occupation and message",
		displayTextArea: false,
		title: "Message",
		type: ControlType.String,
	},
});
addFonts(
	FramerAfUEtwOas,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:persona-main
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PersonaMainFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4b106605c55c3c39deba2a5f4d00793f4f567db70b1a1c3162dfaba628c064cf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var persona_main_default = ComponentWithRoot;
export { persona_main_default as default };
